package com.epic.dlb.model;
// Generated Jun 15, 2018 2:03:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DlbDeviceProfile generated by hbm2java
 */
@Entity
@Table(name="DLB_DEVICE_PROFILE"
    
)
public class DlbDeviceProfile  implements java.io.Serializable {


     private Integer profileId;
     private DlbStatus dlbStatus;
     private String description;
     private Set<DlbWbRiskProfile> dlbWbRiskProfiles = new HashSet<DlbWbRiskProfile>(0);

    public DlbDeviceProfile() {
    }

	
    public DlbDeviceProfile(DlbStatus dlbStatus, String description) {
        this.dlbStatus = dlbStatus;
        this.description = description;
    }
    public DlbDeviceProfile(DlbStatus dlbStatus, String description, Set<DlbWbRiskProfile> dlbWbRiskProfiles) {
       this.dlbStatus = dlbStatus;
       this.description = description;
       this.dlbWbRiskProfiles = dlbWbRiskProfiles;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PROFILE_ID", unique=true, nullable=false)
    public Integer getProfileId() {
        return this.profileId;
    }
    
    public void setProfileId(Integer profileId) {
        this.profileId = profileId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS", nullable=false)
    public DlbStatus getDlbStatus() {
        return this.dlbStatus;
    }
    
    public void setDlbStatus(DlbStatus dlbStatus) {
        this.dlbStatus = dlbStatus;
    }

    
    @Column(name="DESCRIPTION", nullable=false, length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbDeviceProfile")
    public Set<DlbWbRiskProfile> getDlbWbRiskProfiles() {
        return this.dlbWbRiskProfiles;
    }
    
    public void setDlbWbRiskProfiles(Set<DlbWbRiskProfile> dlbWbRiskProfiles) {
        this.dlbWbRiskProfiles = dlbWbRiskProfiles;
    }




}


