package com.epic.dlb.model;
// Generated Jun 15, 2018 2:03:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DlbMissMatchRows generated by hbm2java
 */
@Entity
@Table(name="DLB_MISS_MATCH_ROWS"
    
)
public class DlbMissMatchRows  implements java.io.Serializable {


     private int id;
     private DlbSwtStPurchaseHistory dlbSwtStPurchaseHistory;
     private String desc;
     private String module;
     private Date datetime;

    public DlbMissMatchRows() {
    }

	
    public DlbMissMatchRows(int id) {
        this.id = id;
    }
    public DlbMissMatchRows(int id, DlbSwtStPurchaseHistory dlbSwtStPurchaseHistory, String desc, String module, Date datetime) {
       this.id = id;
       this.dlbSwtStPurchaseHistory = dlbSwtStPurchaseHistory;
       this.desc = desc;
       this.module = module;
       this.datetime = datetime;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PUR_ID")
    public DlbSwtStPurchaseHistory getDlbSwtStPurchaseHistory() {
        return this.dlbSwtStPurchaseHistory;
    }
    
    public void setDlbSwtStPurchaseHistory(DlbSwtStPurchaseHistory dlbSwtStPurchaseHistory) {
        this.dlbSwtStPurchaseHistory = dlbSwtStPurchaseHistory;
    }

    
    @Column(name="DESC")
    public String getDesc() {
        return this.desc;
    }
    
    public void setDesc(String desc) {
        this.desc = desc;
    }

    
    @Column(name="MODULE")
    public String getModule() {
        return this.module;
    }
    
    public void setModule(String module) {
        this.module = module;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATETIME", length=19)
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }




}


