package com.epic.dlb.model;
// Generated Jun 15, 2018 2:03:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DlbSwtStAccountInfo generated by hbm2java
 */
@Entity
@Table(name="DLB_SWT_ST_ACCOUNT_INFO"
    
)
public class DlbSwtStAccountInfo  implements java.io.Serializable {


     private Integer id;
     private String description;
     private String account;
     private Integer tid;
     private Integer mid;
     private String priceCode;
     private Date settlementDate;

    public DlbSwtStAccountInfo() {
    }

    public DlbSwtStAccountInfo(String description, String account, Integer tid, Integer mid, String priceCode, Date settlementDate) {
       this.description = description;
       this.account = account;
       this.tid = tid;
       this.mid = mid;
       this.priceCode = priceCode;
       this.settlementDate = settlementDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="DESCRIPTION", length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="ACCOUNT", length=30)
    public String getAccount() {
        return this.account;
    }
    
    public void setAccount(String account) {
        this.account = account;
    }

    
    @Column(name="TID")
    public Integer getTid() {
        return this.tid;
    }
    
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    
    @Column(name="MID")
    public Integer getMid() {
        return this.mid;
    }
    
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    
    @Column(name="PRICE_CODE", length=10)
    public String getPriceCode() {
        return this.priceCode;
    }
    
    public void setPriceCode(String priceCode) {
        this.priceCode = priceCode;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="SETTLEMENT_DATE", length=10)
    public Date getSettlementDate() {
        return this.settlementDate;
    }
    
    public void setSettlementDate(Date settlementDate) {
        this.settlementDate = settlementDate;
    }




}


