package com.epic.dlb.model;
// Generated Feb 25, 2020 3:52:35 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DlbSwtPurSchedule generated by hbm2java
 */
@Entity
//@Table(name="dlb_swt_pur_schedule"
@Table(name="DLB_SWT_PUR_SCHEDULE"
)
public class DlbSwtPurSchedule  implements java.io.Serializable {


     private Integer schId;
     private DlbStatus dlbStatusBySchStatus;
     private DlbStatus dlbStatusByStatus;
     private DlbSwtMtPaymentMethod dlbSwtMtPaymentMethod;
     private DlbSwtMtRepeat dlbSwtMtRepeat;
     private DlbSwtStWallet dlbSwtStWallet;
     private DlbWbProduct dlbWbProduct;
     private int ticketCount;
     private Date date;
     private String token;
     private Date exeDate;
     private Date createdDate;
     private Set<DlbSwtStPurchaseHistory> dlbSwtStPurchaseHistories = new HashSet<DlbSwtStPurchaseHistory>(0);

    public DlbSwtPurSchedule() {
    }

	
    public DlbSwtPurSchedule(DlbStatus dlbStatusByStatus, DlbSwtMtRepeat dlbSwtMtRepeat, DlbSwtStWallet dlbSwtStWallet, DlbWbProduct dlbWbProduct, int ticketCount) {
        this.dlbStatusByStatus = dlbStatusByStatus;
        this.dlbSwtMtRepeat = dlbSwtMtRepeat;
        this.dlbSwtStWallet = dlbSwtStWallet;
        this.dlbWbProduct = dlbWbProduct;
        this.ticketCount = ticketCount;
    }
    public DlbSwtPurSchedule(DlbStatus dlbStatusBySchStatus, DlbStatus dlbStatusByStatus, DlbSwtMtPaymentMethod dlbSwtMtPaymentMethod, DlbSwtMtRepeat dlbSwtMtRepeat, DlbSwtStWallet dlbSwtStWallet, DlbWbProduct dlbWbProduct, int ticketCount, Date date, String token, Date exeDate, Date createdDate, Set<DlbSwtStPurchaseHistory> dlbSwtStPurchaseHistories) {
       this.dlbStatusBySchStatus = dlbStatusBySchStatus;
       this.dlbStatusByStatus = dlbStatusByStatus;
       this.dlbSwtMtPaymentMethod = dlbSwtMtPaymentMethod;
       this.dlbSwtMtRepeat = dlbSwtMtRepeat;
       this.dlbSwtStWallet = dlbSwtStWallet;
       this.dlbWbProduct = dlbWbProduct;
       this.ticketCount = ticketCount;
       this.date = date;
       this.token = token;
       this.exeDate = exeDate;
       this.createdDate = createdDate;
       this.dlbSwtStPurchaseHistories = dlbSwtStPurchaseHistories;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="SCH_ID", unique=true, nullable=false)
    public Integer getSchId() {
        return this.schId;
    }
    
    public void setSchId(Integer schId) {
        this.schId = schId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SCH_STATUS")
    public DlbStatus getDlbStatusBySchStatus() {
        return this.dlbStatusBySchStatus;
    }
    
    public void setDlbStatusBySchStatus(DlbStatus dlbStatusBySchStatus) {
        this.dlbStatusBySchStatus = dlbStatusBySchStatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS", nullable=false)
    public DlbStatus getDlbStatusByStatus() {
        return this.dlbStatusByStatus;
    }
    
    public void setDlbStatusByStatus(DlbStatus dlbStatusByStatus) {
        this.dlbStatusByStatus = dlbStatusByStatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PAYMETHOD")
    public DlbSwtMtPaymentMethod getDlbSwtMtPaymentMethod() {
        return this.dlbSwtMtPaymentMethod;
    }
    
    public void setDlbSwtMtPaymentMethod(DlbSwtMtPaymentMethod dlbSwtMtPaymentMethod) {
        this.dlbSwtMtPaymentMethod = dlbSwtMtPaymentMethod;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="REPEAT_ID", nullable=false)
    public DlbSwtMtRepeat getDlbSwtMtRepeat() {
        return this.dlbSwtMtRepeat;
    }
    
    public void setDlbSwtMtRepeat(DlbSwtMtRepeat dlbSwtMtRepeat) {
        this.dlbSwtMtRepeat = dlbSwtMtRepeat;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="WALLET_ID", nullable=false)
    public DlbSwtStWallet getDlbSwtStWallet() {
        return this.dlbSwtStWallet;
    }
    
    public void setDlbSwtStWallet(DlbSwtStWallet dlbSwtStWallet) {
        this.dlbSwtStWallet = dlbSwtStWallet;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PRO_ID", nullable=false)
    public DlbWbProduct getDlbWbProduct() {
        return this.dlbWbProduct;
    }
    
    public void setDlbWbProduct(DlbWbProduct dlbWbProduct) {
        this.dlbWbProduct = dlbWbProduct;
    }

    
    @Column(name="TICKET_COUNT", nullable=false)
    public int getTicketCount() {
        return this.ticketCount;
    }
    
    public void setTicketCount(int ticketCount) {
        this.ticketCount = ticketCount;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATE", length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="TOKEN")
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EXE_DATE", length=19)
    public Date getExeDate() {
        return this.exeDate;
    }
    
    public void setExeDate(Date exeDate) {
        this.exeDate = exeDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbSwtPurSchedule")
    public Set<DlbSwtStPurchaseHistory> getDlbSwtStPurchaseHistories() {
        return this.dlbSwtStPurchaseHistories;
    }
    
    public void setDlbSwtStPurchaseHistories(Set<DlbSwtStPurchaseHistory> dlbSwtStPurchaseHistories) {
        this.dlbSwtStPurchaseHistories = dlbSwtStPurchaseHistories;
    }




}


