package com.epic.dlb.model;
// Generated Jun 15, 2018 2:03:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DlbSwtStMapResponseCode generated by hbm2java
 */
@Entity
@Table(name="DLB_SWT_ST_MAP_RESPONSE_CODE"
    
)
public class DlbSwtStMapResponseCode  implements java.io.Serializable {


     private String hostCode;
     private String epicCode;
     private String description;
     private Set<DlbSwtStTransaction> dlbSwtStTransactions = new HashSet<DlbSwtStTransaction>(0);

    public DlbSwtStMapResponseCode() {
    }

	
    public DlbSwtStMapResponseCode(String hostCode) {
        this.hostCode = hostCode;
    }
    public DlbSwtStMapResponseCode(String hostCode, String epicCode, String description, Set<DlbSwtStTransaction> dlbSwtStTransactions) {
       this.hostCode = hostCode;
       this.epicCode = epicCode;
       this.description = description;
       this.dlbSwtStTransactions = dlbSwtStTransactions;
    }
   
     @Id 

    
    @Column(name="HOST_CODE", unique=true, nullable=false, length=3)
    public String getHostCode() {
        return this.hostCode;
    }
    
    public void setHostCode(String hostCode) {
        this.hostCode = hostCode;
    }

    
    @Column(name="EPIC_CODE", length=4)
    public String getEpicCode() {
        return this.epicCode;
    }
    
    public void setEpicCode(String epicCode) {
        this.epicCode = epicCode;
    }

    
    @Column(name="DESCRIPTION", length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbSwtStMapResponseCode")
    public Set<DlbSwtStTransaction> getDlbSwtStTransactions() {
        return this.dlbSwtStTransactions;
    }
    
    public void setDlbSwtStTransactions(Set<DlbSwtStTransaction> dlbSwtStTransactions) {
        this.dlbSwtStTransactions = dlbSwtStTransactions;
    }




}


