package com.epic.dlb.model;
// Generated Aug 30, 2018 5:13:41 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DlbSwtMtConfiguration generated by hbm2java
 */
@Entity
@Table(name="DLB_SWT_MT_CONFIGURATION"
    
)
public class DlbSwtMtConfiguration  implements java.io.Serializable {


     private Integer id;
     private DlbStatus dlbStatusByStatus;
     private DlbStatus dlbStatusByLogBackupStatus;
     private int minPool;
     private int maxPool;
     private int maxQueueSize;
     private String logBackupPath;
     private Integer nofLogFileMaintain;
     private int logLevel;
     private String hnbJustpayUrl;
     private String hnbFundtrnsUrl;
     private String hnbJpBearid;
     private String hnbFtBearid;
     private String hnbInsId;
     private String hnbAppId;
     private String ezCashUrl;
     private String ezCashTimeout;
     private String ezCashPassword;
     private String ezCashUser;
     private String epicMid;
     private Integer listenerTxnPort;
     private String smppPrimaryIp;
     private String smppPrimarySystemId;
     private String smppPrimaryPassword;
     private String smppPrimarySrcNumber;
     private Integer smppPrimaryPort;
     private Integer smppPrimaryTimeout;
     private String smppSecondaryIp;
     private String smppSecondarySystemId;
     private String smppSecondaryPassword;
     private String smppSecondarySrcNumber;
     private Integer smppSecondaryPort;
     private Integer smppSecondaryTimeout;
     private Integer smppRoundRobinEnabled;
     private Integer listenerUploadPort;
     private Integer listenerUploadTimeout;
     private Integer listenerTxnTimeout;
     private String epicTid;
     private String MCashUrl;
     private String MCashTimeout;
     private String MCashPassword;
     private String MCashUser;
     private Integer otpExpire;
     private Integer checkoutExpire;
     private Integer checkoutThreadSleep;
     private String hnbBankCode;
     private String mobSessTimeout;
     private Integer maxPinAttempts;
     private String randomAmountLimit;
     private String pushUrl;
     private Integer pushTimeout;
     private String pushRequestMethod;
     private String pushReqKey;
     private String pushReqValue;
     private String pushApiKey;
     private String ezCashAlias;
     private String ezCashPin;
     private String switchIp;
     private Integer switchPort;
     private Integer scheduleTicketThreadSleep;

    public DlbSwtMtConfiguration() {
    }

	
    public DlbSwtMtConfiguration(DlbStatus dlbStatusByStatus, DlbStatus dlbStatusByLogBackupStatus, int minPool, int maxPool, int maxQueueSize, String logBackupPath, int logLevel) {
        this.dlbStatusByStatus = dlbStatusByStatus;
        this.dlbStatusByLogBackupStatus = dlbStatusByLogBackupStatus;
        this.minPool = minPool;
        this.maxPool = maxPool;
        this.maxQueueSize = maxQueueSize;
        this.logBackupPath = logBackupPath;
        this.logLevel = logLevel;
    }
    public DlbSwtMtConfiguration(DlbStatus dlbStatusByStatus, DlbStatus dlbStatusByLogBackupStatus, int minPool, int maxPool, int maxQueueSize, String logBackupPath, Integer nofLogFileMaintain, int logLevel, String hnbJustpayUrl, String hnbFundtrnsUrl, String hnbJpBearid, String hnbFtBearid, String hnbInsId, String hnbAppId, String ezCashUrl, String ezCashTimeout, String ezCashPassword, String ezCashUser, String epicMid, Integer listenerTxnPort, String smppPrimaryIp, String smppPrimarySystemId, String smppPrimaryPassword, String smppPrimarySrcNumber, Integer smppPrimaryPort, Integer smppPrimaryTimeout, String smppSecondaryIp, String smppSecondarySystemId, String smppSecondaryPassword, String smppSecondarySrcNumber, Integer smppSecondaryPort, Integer smppSecondaryTimeout, Integer smppRoundRobinEnabled, Integer listenerUploadPort, Integer listenerUploadTimeout, Integer listenerTxnTimeout, String epicTid, String MCashUrl, String MCashTimeout, String MCashPassword, String MCashUser, Integer otpExpire, Integer checkoutExpire, Integer checkoutThreadSleep, String hnbBankCode, String mobSessTimeout, Integer maxPinAttempts, String randomAmountLimit, String pushUrl, Integer pushTimeout, String pushRequestMethod, String pushReqKey, String pushReqValue, String pushApiKey, String ezCashAlias, String ezCashPin, String switchIp, Integer switchPort, Integer scheduleTicketThreadSleep) {
       this.dlbStatusByStatus = dlbStatusByStatus;
       this.dlbStatusByLogBackupStatus = dlbStatusByLogBackupStatus;
       this.minPool = minPool;
       this.maxPool = maxPool;
       this.maxQueueSize = maxQueueSize;
       this.logBackupPath = logBackupPath;
       this.nofLogFileMaintain = nofLogFileMaintain;
       this.logLevel = logLevel;
       this.hnbJustpayUrl = hnbJustpayUrl;
       this.hnbFundtrnsUrl = hnbFundtrnsUrl;
       this.hnbJpBearid = hnbJpBearid;
       this.hnbFtBearid = hnbFtBearid;
       this.hnbInsId = hnbInsId;
       this.hnbAppId = hnbAppId;
       this.ezCashUrl = ezCashUrl;
       this.ezCashTimeout = ezCashTimeout;
       this.ezCashPassword = ezCashPassword;
       this.ezCashUser = ezCashUser;
       this.epicMid = epicMid;
       this.listenerTxnPort = listenerTxnPort;
       this.smppPrimaryIp = smppPrimaryIp;
       this.smppPrimarySystemId = smppPrimarySystemId;
       this.smppPrimaryPassword = smppPrimaryPassword;
       this.smppPrimarySrcNumber = smppPrimarySrcNumber;
       this.smppPrimaryPort = smppPrimaryPort;
       this.smppPrimaryTimeout = smppPrimaryTimeout;
       this.smppSecondaryIp = smppSecondaryIp;
       this.smppSecondarySystemId = smppSecondarySystemId;
       this.smppSecondaryPassword = smppSecondaryPassword;
       this.smppSecondarySrcNumber = smppSecondarySrcNumber;
       this.smppSecondaryPort = smppSecondaryPort;
       this.smppSecondaryTimeout = smppSecondaryTimeout;
       this.smppRoundRobinEnabled = smppRoundRobinEnabled;
       this.listenerUploadPort = listenerUploadPort;
       this.listenerUploadTimeout = listenerUploadTimeout;
       this.listenerTxnTimeout = listenerTxnTimeout;
       this.epicTid = epicTid;
       this.MCashUrl = MCashUrl;
       this.MCashTimeout = MCashTimeout;
       this.MCashPassword = MCashPassword;
       this.MCashUser = MCashUser;
       this.otpExpire = otpExpire;
       this.checkoutExpire = checkoutExpire;
       this.checkoutThreadSleep = checkoutThreadSleep;
       this.hnbBankCode = hnbBankCode;
       this.mobSessTimeout = mobSessTimeout;
       this.maxPinAttempts = maxPinAttempts;
       this.randomAmountLimit = randomAmountLimit;
       this.pushUrl = pushUrl;
       this.pushTimeout = pushTimeout;
       this.pushRequestMethod = pushRequestMethod;
       this.pushReqKey = pushReqKey;
       this.pushReqValue = pushReqValue;
       this.pushApiKey = pushApiKey;
       this.ezCashAlias = ezCashAlias;
       this.ezCashPin = ezCashPin;
       this.switchIp = switchIp;
       this.switchPort = switchPort;
       this.scheduleTicketThreadSleep = scheduleTicketThreadSleep;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS", nullable=false)
    public DlbStatus getDlbStatusByStatus() {
        return this.dlbStatusByStatus;
    }
    
    public void setDlbStatusByStatus(DlbStatus dlbStatusByStatus) {
        this.dlbStatusByStatus = dlbStatusByStatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="LOG_BACKUP_STATUS", nullable=false)
    public DlbStatus getDlbStatusByLogBackupStatus() {
        return this.dlbStatusByLogBackupStatus;
    }
    
    public void setDlbStatusByLogBackupStatus(DlbStatus dlbStatusByLogBackupStatus) {
        this.dlbStatusByLogBackupStatus = dlbStatusByLogBackupStatus;
    }

    
    @Column(name="MIN_POOL", nullable=false)
    public int getMinPool() {
        return this.minPool;
    }
    
    public void setMinPool(int minPool) {
        this.minPool = minPool;
    }

    
    @Column(name="MAX_POOL", nullable=false)
    public int getMaxPool() {
        return this.maxPool;
    }
    
    public void setMaxPool(int maxPool) {
        this.maxPool = maxPool;
    }

    
    @Column(name="MAX_QUEUE_SIZE", nullable=false)
    public int getMaxQueueSize() {
        return this.maxQueueSize;
    }
    
    public void setMaxQueueSize(int maxQueueSize) {
        this.maxQueueSize = maxQueueSize;
    }

    
    @Column(name="LOG_BACKUP_PATH", nullable=false, length=200)
    public String getLogBackupPath() {
        return this.logBackupPath;
    }
    
    public void setLogBackupPath(String logBackupPath) {
        this.logBackupPath = logBackupPath;
    }

    
    @Column(name="NOF_LOG_FILE_MAINTAIN")
    public Integer getNofLogFileMaintain() {
        return this.nofLogFileMaintain;
    }
    
    public void setNofLogFileMaintain(Integer nofLogFileMaintain) {
        this.nofLogFileMaintain = nofLogFileMaintain;
    }

    
    @Column(name="LOG_LEVEL", nullable=false)
    public int getLogLevel() {
        return this.logLevel;
    }
    
    public void setLogLevel(int logLevel) {
        this.logLevel = logLevel;
    }

    
    @Column(name="HNB_JUSTPAY_URL", length=500)
    public String getHnbJustpayUrl() {
        return this.hnbJustpayUrl;
    }
    
    public void setHnbJustpayUrl(String hnbJustpayUrl) {
        this.hnbJustpayUrl = hnbJustpayUrl;
    }

    
    @Column(name="HNB_FUNDTRNS_URL")
    public String getHnbFundtrnsUrl() {
        return this.hnbFundtrnsUrl;
    }
    
    public void setHnbFundtrnsUrl(String hnbFundtrnsUrl) {
        this.hnbFundtrnsUrl = hnbFundtrnsUrl;
    }

    
    @Column(name="HNB_JP_BEARID", length=45)
    public String getHnbJpBearid() {
        return this.hnbJpBearid;
    }
    
    public void setHnbJpBearid(String hnbJpBearid) {
        this.hnbJpBearid = hnbJpBearid;
    }

    
    @Column(name="HNB_FT_BEARID", length=45)
    public String getHnbFtBearid() {
        return this.hnbFtBearid;
    }
    
    public void setHnbFtBearid(String hnbFtBearid) {
        this.hnbFtBearid = hnbFtBearid;
    }

    
    @Column(name="HNB_INS_ID", length=50)
    public String getHnbInsId() {
        return this.hnbInsId;
    }
    
    public void setHnbInsId(String hnbInsId) {
        this.hnbInsId = hnbInsId;
    }

    
    @Column(name="HNB_APP_ID", length=45)
    public String getHnbAppId() {
        return this.hnbAppId;
    }
    
    public void setHnbAppId(String hnbAppId) {
        this.hnbAppId = hnbAppId;
    }

    
    @Column(name="EZ_CASH_URL", length=500)
    public String getEzCashUrl() {
        return this.ezCashUrl;
    }
    
    public void setEzCashUrl(String ezCashUrl) {
        this.ezCashUrl = ezCashUrl;
    }

    
    @Column(name="EZ_CASH_TIMEOUT", length=45)
    public String getEzCashTimeout() {
        return this.ezCashTimeout;
    }
    
    public void setEzCashTimeout(String ezCashTimeout) {
        this.ezCashTimeout = ezCashTimeout;
    }

    
    @Column(name="EZ_CASH_PASSWORD", length=45)
    public String getEzCashPassword() {
        return this.ezCashPassword;
    }
    
    public void setEzCashPassword(String ezCashPassword) {
        this.ezCashPassword = ezCashPassword;
    }

    
    @Column(name="EZ_CASH_USER", length=45)
    public String getEzCashUser() {
        return this.ezCashUser;
    }
    
    public void setEzCashUser(String ezCashUser) {
        this.ezCashUser = ezCashUser;
    }

    
    @Column(name="EPIC_MID", length=15)
    public String getEpicMid() {
        return this.epicMid;
    }
    
    public void setEpicMid(String epicMid) {
        this.epicMid = epicMid;
    }

    
    @Column(name="LISTENER_TXN_PORT")
    public Integer getListenerTxnPort() {
        return this.listenerTxnPort;
    }
    
    public void setListenerTxnPort(Integer listenerTxnPort) {
        this.listenerTxnPort = listenerTxnPort;
    }

    
    @Column(name="SMPP_PRIMARY_IP", length=15)
    public String getSmppPrimaryIp() {
        return this.smppPrimaryIp;
    }
    
    public void setSmppPrimaryIp(String smppPrimaryIp) {
        this.smppPrimaryIp = smppPrimaryIp;
    }

    
    @Column(name="SMPP_PRIMARY_SYSTEM_ID", length=10)
    public String getSmppPrimarySystemId() {
        return this.smppPrimarySystemId;
    }
    
    public void setSmppPrimarySystemId(String smppPrimarySystemId) {
        this.smppPrimarySystemId = smppPrimarySystemId;
    }

    
    @Column(name="SMPP_PRIMARY_PASSWORD", length=10)
    public String getSmppPrimaryPassword() {
        return this.smppPrimaryPassword;
    }
    
    public void setSmppPrimaryPassword(String smppPrimaryPassword) {
        this.smppPrimaryPassword = smppPrimaryPassword;
    }

    
    @Column(name="SMPP_PRIMARY_SRC_NUMBER", length=20)
    public String getSmppPrimarySrcNumber() {
        return this.smppPrimarySrcNumber;
    }
    
    public void setSmppPrimarySrcNumber(String smppPrimarySrcNumber) {
        this.smppPrimarySrcNumber = smppPrimarySrcNumber;
    }

    
    @Column(name="SMPP_PRIMARY_PORT")
    public Integer getSmppPrimaryPort() {
        return this.smppPrimaryPort;
    }
    
    public void setSmppPrimaryPort(Integer smppPrimaryPort) {
        this.smppPrimaryPort = smppPrimaryPort;
    }

    
    @Column(name="SMPP_PRIMARY_TIMEOUT")
    public Integer getSmppPrimaryTimeout() {
        return this.smppPrimaryTimeout;
    }
    
    public void setSmppPrimaryTimeout(Integer smppPrimaryTimeout) {
        this.smppPrimaryTimeout = smppPrimaryTimeout;
    }

    
    @Column(name="SMPP_SECONDARY_IP", length=15)
    public String getSmppSecondaryIp() {
        return this.smppSecondaryIp;
    }
    
    public void setSmppSecondaryIp(String smppSecondaryIp) {
        this.smppSecondaryIp = smppSecondaryIp;
    }

    
    @Column(name="SMPP_SECONDARY_SYSTEM_ID", length=10)
    public String getSmppSecondarySystemId() {
        return this.smppSecondarySystemId;
    }
    
    public void setSmppSecondarySystemId(String smppSecondarySystemId) {
        this.smppSecondarySystemId = smppSecondarySystemId;
    }

    
    @Column(name="SMPP_SECONDARY_PASSWORD", length=10)
    public String getSmppSecondaryPassword() {
        return this.smppSecondaryPassword;
    }
    
    public void setSmppSecondaryPassword(String smppSecondaryPassword) {
        this.smppSecondaryPassword = smppSecondaryPassword;
    }

    
    @Column(name="SMPP_SECONDARY_SRC_NUMBER", length=20)
    public String getSmppSecondarySrcNumber() {
        return this.smppSecondarySrcNumber;
    }
    
    public void setSmppSecondarySrcNumber(String smppSecondarySrcNumber) {
        this.smppSecondarySrcNumber = smppSecondarySrcNumber;
    }

    
    @Column(name="SMPP_SECONDARY_PORT")
    public Integer getSmppSecondaryPort() {
        return this.smppSecondaryPort;
    }
    
    public void setSmppSecondaryPort(Integer smppSecondaryPort) {
        this.smppSecondaryPort = smppSecondaryPort;
    }

    
    @Column(name="SMPP_SECONDARY_TIMEOUT")
    public Integer getSmppSecondaryTimeout() {
        return this.smppSecondaryTimeout;
    }
    
    public void setSmppSecondaryTimeout(Integer smppSecondaryTimeout) {
        this.smppSecondaryTimeout = smppSecondaryTimeout;
    }

    
    @Column(name="SMPP_ROUND_ROBIN_ENABLED")
    public Integer getSmppRoundRobinEnabled() {
        return this.smppRoundRobinEnabled;
    }
    
    public void setSmppRoundRobinEnabled(Integer smppRoundRobinEnabled) {
        this.smppRoundRobinEnabled = smppRoundRobinEnabled;
    }

    
    @Column(name="LISTENER_UPLOAD_PORT")
    public Integer getListenerUploadPort() {
        return this.listenerUploadPort;
    }
    
    public void setListenerUploadPort(Integer listenerUploadPort) {
        this.listenerUploadPort = listenerUploadPort;
    }

    
    @Column(name="LISTENER_UPLOAD_TIMEOUT")
    public Integer getListenerUploadTimeout() {
        return this.listenerUploadTimeout;
    }
    
    public void setListenerUploadTimeout(Integer listenerUploadTimeout) {
        this.listenerUploadTimeout = listenerUploadTimeout;
    }

    
    @Column(name="LISTENER_TXN_TIMEOUT")
    public Integer getListenerTxnTimeout() {
        return this.listenerTxnTimeout;
    }
    
    public void setListenerTxnTimeout(Integer listenerTxnTimeout) {
        this.listenerTxnTimeout = listenerTxnTimeout;
    }

    
    @Column(name="EPIC_TID", length=45)
    public String getEpicTid() {
        return this.epicTid;
    }
    
    public void setEpicTid(String epicTid) {
        this.epicTid = epicTid;
    }

    
    @Column(name="M_CASH_URL", length=100)
    public String getMCashUrl() {
        return this.MCashUrl;
    }
    
    public void setMCashUrl(String MCashUrl) {
        this.MCashUrl = MCashUrl;
    }

    
    @Column(name="M_CASH_TIMEOUT", length=45)
    public String getMCashTimeout() {
        return this.MCashTimeout;
    }
    
    public void setMCashTimeout(String MCashTimeout) {
        this.MCashTimeout = MCashTimeout;
    }

    
    @Column(name="M_CASH_PASSWORD", length=45)
    public String getMCashPassword() {
        return this.MCashPassword;
    }
    
    public void setMCashPassword(String MCashPassword) {
        this.MCashPassword = MCashPassword;
    }

    
    @Column(name="M_CASH_USER", length=45)
    public String getMCashUser() {
        return this.MCashUser;
    }
    
    public void setMCashUser(String MCashUser) {
        this.MCashUser = MCashUser;
    }

    
    @Column(name="OTP_EXPIRE")
    public Integer getOtpExpire() {
        return this.otpExpire;
    }
    
    public void setOtpExpire(Integer otpExpire) {
        this.otpExpire = otpExpire;
    }

    
    @Column(name="CHECKOUT_EXPIRE")
    public Integer getCheckoutExpire() {
        return this.checkoutExpire;
    }
    
    public void setCheckoutExpire(Integer checkoutExpire) {
        this.checkoutExpire = checkoutExpire;
    }

    
    @Column(name="CHECKOUT_THREAD_SLEEP")
    public Integer getCheckoutThreadSleep() {
        return this.checkoutThreadSleep;
    }
    
    public void setCheckoutThreadSleep(Integer checkoutThreadSleep) {
        this.checkoutThreadSleep = checkoutThreadSleep;
    }

    
    @Column(name="HNB_BANK_CODE", length=8)
    public String getHnbBankCode() {
        return this.hnbBankCode;
    }
    
    public void setHnbBankCode(String hnbBankCode) {
        this.hnbBankCode = hnbBankCode;
    }

    
    @Column(name="MOB_SESS_TIMEOUT", length=2)
    public String getMobSessTimeout() {
        return this.mobSessTimeout;
    }
    
    public void setMobSessTimeout(String mobSessTimeout) {
        this.mobSessTimeout = mobSessTimeout;
    }

    
    @Column(name="MAX_PIN_ATTEMPTS")
    public Integer getMaxPinAttempts() {
        return this.maxPinAttempts;
    }
    
    public void setMaxPinAttempts(Integer maxPinAttempts) {
        this.maxPinAttempts = maxPinAttempts;
    }

    
    @Column(name="RANDOM_AMOUNT_LIMIT", length=10)
    public String getRandomAmountLimit() {
        return this.randomAmountLimit;
    }
    
    public void setRandomAmountLimit(String randomAmountLimit) {
        this.randomAmountLimit = randomAmountLimit;
    }

    
    @Column(name="PUSH_URL", length=100)
    public String getPushUrl() {
        return this.pushUrl;
    }
    
    public void setPushUrl(String pushUrl) {
        this.pushUrl = pushUrl;
    }

    
    @Column(name="PUSH_TIMEOUT")
    public Integer getPushTimeout() {
        return this.pushTimeout;
    }
    
    public void setPushTimeout(Integer pushTimeout) {
        this.pushTimeout = pushTimeout;
    }

    
    @Column(name="PUSH_REQUEST_METHOD", length=20)
    public String getPushRequestMethod() {
        return this.pushRequestMethod;
    }
    
    public void setPushRequestMethod(String pushRequestMethod) {
        this.pushRequestMethod = pushRequestMethod;
    }

    
    @Column(name="PUSH_REQ_KEY", length=45)
    public String getPushReqKey() {
        return this.pushReqKey;
    }
    
    public void setPushReqKey(String pushReqKey) {
        this.pushReqKey = pushReqKey;
    }

    
    @Column(name="PUSH_REQ_VALUE", length=45)
    public String getPushReqValue() {
        return this.pushReqValue;
    }
    
    public void setPushReqValue(String pushReqValue) {
        this.pushReqValue = pushReqValue;
    }

    
    @Column(name="PUSH_API_KEY", length=200)
    public String getPushApiKey() {
        return this.pushApiKey;
    }
    
    public void setPushApiKey(String pushApiKey) {
        this.pushApiKey = pushApiKey;
    }

    
    @Column(name="EZ_CASH_ALIAS", length=50)
    public String getEzCashAlias() {
        return this.ezCashAlias;
    }
    
    public void setEzCashAlias(String ezCashAlias) {
        this.ezCashAlias = ezCashAlias;
    }

    
    @Column(name="EZ_CASH_PIN", length=4)
    public String getEzCashPin() {
        return this.ezCashPin;
    }
    
    public void setEzCashPin(String ezCashPin) {
        this.ezCashPin = ezCashPin;
    }

    
    @Column(name="SWITCH_IP", length=20)
    public String getSwitchIp() {
        return this.switchIp;
    }
    
    public void setSwitchIp(String switchIp) {
        this.switchIp = switchIp;
    }

    
    @Column(name="SWITCH_PORT")
    public Integer getSwitchPort() {
        return this.switchPort;
    }
    
    public void setSwitchPort(Integer switchPort) {
        this.switchPort = switchPort;
    }

    
    @Column(name="SCHEDULE_TICKET_THREAD_SLEEP")
    public Integer getScheduleTicketThreadSleep() {
        return this.scheduleTicketThreadSleep;
    }
    
    public void setScheduleTicketThreadSleep(Integer scheduleTicketThreadSleep) {
        this.scheduleTicketThreadSleep = scheduleTicketThreadSleep;
    }




}


