package com.epic.dlb.model;
// Generated Feb 25, 2020 3:52:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DlbSwtMtRepeat generated by hbm2java
 */
@Entity
@Table(name="dlb_swt_mt_repeat"
)
public class DlbSwtMtRepeat  implements java.io.Serializable {


     private Integer repeatId;
     private String desc;
     private Set<DlbSwtPurSchedule> dlbSwtPurSchedules = new HashSet<DlbSwtPurSchedule>(0);

    public DlbSwtMtRepeat() {
    }

	
    public DlbSwtMtRepeat(String desc) {
        this.desc = desc;
    }
    public DlbSwtMtRepeat(String desc, Set<DlbSwtPurSchedule> dlbSwtPurSchedules) {
       this.desc = desc;
       this.dlbSwtPurSchedules = dlbSwtPurSchedules;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="REPEAT_ID", unique=true, nullable=false)
    public Integer getRepeatId() {
        return this.repeatId;
    }
    
    public void setRepeatId(Integer repeatId) {
        this.repeatId = repeatId;
    }

    
    @Column(name="DESC", nullable=false)
    public String getDesc() {
        return this.desc;
    }
    
    public void setDesc(String desc) {
        this.desc = desc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbSwtMtRepeat")
    public Set<DlbSwtPurSchedule> getDlbSwtPurSchedules() {
        return this.dlbSwtPurSchedules;
    }
    
    public void setDlbSwtPurSchedules(Set<DlbSwtPurSchedule> dlbSwtPurSchedules) {
        this.dlbSwtPurSchedules = dlbSwtPurSchedules;
    }




}


