package com.epic.dlb.model;
// Generated Oct 1, 2018 7:23:18 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * DlbSwtStTransaction generated by hbm2java
 */
@Entity
@Table(name="DLB_SWT_ST_TRANSACTION"
  
)
public class DlbSwtStTransaction  implements java.io.Serializable {


     private String txnid;
     private DlbStatus dlbStatus;
     private DlbSwtMtChannelType dlbSwtMtChannelType;
     private DlbSwtMtPaymentMethod dlbSwtMtPaymentMethod;
     private DlbSwtMtTxnType dlbSwtMtTxnType;
     private DlbSwtStMapResponseCode dlbSwtStMapResponseCode;
     private DlbSwtStWallet dlbSwtStWallet;
     private String responseCode;
     private String tid;
     private String mid;
     private String traceno;
     private String amount;
     private String rrn;
     private String token;
     private String bankcode;
     private String dateTime;
     private Date updatedtime;
     private String serviceCharge;
     private String refno;
     private Integer schId;
     private String holderName;
     private String toAccount;
     private String fromAccount;
     private String regAccount;
     private String ceftDescription;
     private DlbEzCashCheck dlbEzCashCheck;
     private Set<DlbSwtStTransactionHistory> dlbSwtStTransactionHistories = new HashSet<DlbSwtStTransactionHistory>(0);
     
      private String referenceNo;    
      private String bank;    

    public DlbSwtStTransaction() {
    }

	
    public DlbSwtStTransaction(String txnid, DlbSwtMtTxnType dlbSwtMtTxnType, Date updatedtime) {
        this.txnid = txnid;
        this.dlbSwtMtTxnType = dlbSwtMtTxnType;
        this.updatedtime = updatedtime;
    }
    public DlbSwtStTransaction(String txnid, DlbStatus dlbStatus, DlbSwtMtChannelType dlbSwtMtChannelType, DlbSwtMtPaymentMethod dlbSwtMtPaymentMethod, DlbSwtMtTxnType dlbSwtMtTxnType, DlbSwtStMapResponseCode dlbSwtStMapResponseCode, DlbSwtStWallet dlbSwtStWallet, String responseCode, String tid, String mid, String traceno, String amount, String rrn, String token, String bankcode, String dateTime, Date updatedtime, String serviceCharge, String refno, Integer schId, String holderName, String toAccount, String fromAccount, String regAccount, String ceftDescription, DlbEzCashCheck dlbEzCashCheck, Set<DlbSwtStTransactionHistory> dlbSwtStTransactionHistories) {
       this.txnid = txnid;
       this.dlbStatus = dlbStatus;
       this.dlbSwtMtChannelType = dlbSwtMtChannelType;
       this.dlbSwtMtPaymentMethod = dlbSwtMtPaymentMethod;
       this.dlbSwtMtTxnType = dlbSwtMtTxnType;
       this.dlbSwtStMapResponseCode = dlbSwtStMapResponseCode;
       this.dlbSwtStWallet = dlbSwtStWallet;
       this.responseCode = responseCode;
       this.tid = tid;
       this.mid = mid;
       this.traceno = traceno;
       this.amount = amount;
       this.rrn = rrn;
       this.token = token;
       this.bankcode = bankcode;
       this.dateTime = dateTime;
       this.updatedtime = updatedtime;
       this.serviceCharge = serviceCharge;
       this.refno = refno;
       this.schId = schId;
       this.holderName = holderName;
       this.toAccount = toAccount;
       this.fromAccount = fromAccount;
       this.regAccount = regAccount;
       this.ceftDescription = ceftDescription;
       this.dlbEzCashCheck = dlbEzCashCheck;
       this.dlbSwtStTransactionHistories = dlbSwtStTransactionHistories;
    }
   
     @Id 

    
    @Column(name="TXNID", unique=true, nullable=false, length=32)
    public String getTxnid() {
        return this.txnid;
    }
    
    public void setTxnid(String txnid) {
        this.txnid = txnid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS")
    public DlbStatus getDlbStatus() {
        return this.dlbStatus;
    }
    
    public void setDlbStatus(DlbStatus dlbStatus) {
        this.dlbStatus = dlbStatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CHANNEL_TYPE")
    public DlbSwtMtChannelType getDlbSwtMtChannelType() {
        return this.dlbSwtMtChannelType;
    }
    
    public void setDlbSwtMtChannelType(DlbSwtMtChannelType dlbSwtMtChannelType) {
        this.dlbSwtMtChannelType = dlbSwtMtChannelType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PAY_METHOD")
    public DlbSwtMtPaymentMethod getDlbSwtMtPaymentMethod() {
        return this.dlbSwtMtPaymentMethod;
    }
    
    public void setDlbSwtMtPaymentMethod(DlbSwtMtPaymentMethod dlbSwtMtPaymentMethod) {
        this.dlbSwtMtPaymentMethod = dlbSwtMtPaymentMethod;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TXNTYPE", nullable=false)
    public DlbSwtMtTxnType getDlbSwtMtTxnType() {
        return this.dlbSwtMtTxnType;
    }
    
    public void setDlbSwtMtTxnType(DlbSwtMtTxnType dlbSwtMtTxnType) {
        this.dlbSwtMtTxnType = dlbSwtMtTxnType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="HOST_RC")
    public DlbSwtStMapResponseCode getDlbSwtStMapResponseCode() {
        return this.dlbSwtStMapResponseCode;
    }
    
    public void setDlbSwtStMapResponseCode(DlbSwtStMapResponseCode dlbSwtStMapResponseCode) {
        this.dlbSwtStMapResponseCode = dlbSwtStMapResponseCode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="WALLETID")
    public DlbSwtStWallet getDlbSwtStWallet() {
        return this.dlbSwtStWallet;
    }
    
    public void setDlbSwtStWallet(DlbSwtStWallet dlbSwtStWallet) {
        this.dlbSwtStWallet = dlbSwtStWallet;
    }

    
    @Column(name="RESPONSE_CODE", length=4)
    public String getResponseCode() {
        return this.responseCode;
    }
    
    public void setResponseCode(String responseCode) {
        this.responseCode = responseCode;
    }

    
    @Column(name="TID", length=45)
    public String getTid() {
        return this.tid;
    }
    
    public void setTid(String tid) {
        this.tid = tid;
    }

    
    @Column(name="MID", length=45)
    public String getMid() {
        return this.mid;
    }
    
    public void setMid(String mid) {
        this.mid = mid;
    }

    
    @Column(name="TRACENO", length=45)
    public String getTraceno() {
        return this.traceno;
    }
    
    public void setTraceno(String traceno) {
        this.traceno = traceno;
    }

    
    @Column(name="AMOUNT", length=45)
    public String getAmount() {
        return this.amount;
    }
    
    public void setAmount(String amount) {
        this.amount = amount;
    }

    
    @Column(name="RRN", length=100)
    public String getRrn() {
        return this.rrn;
    }
    
    public void setRrn(String rrn) {
        this.rrn = rrn;
    }

    
    @Column(name="TOKEN", length=45)
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }

    
    @Column(name="BANKCODE", length=45)
    public String getBankcode() {
        return this.bankcode;
    }
    
    public void setBankcode(String bankcode) {
        this.bankcode = bankcode;
    }

    
    @Column(name="DATE_TIME", length=45)
    public String getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(String dateTime) {
        this.dateTime = dateTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATEDTIME", nullable=false, length=19)
    public Date getUpdatedtime() {
        return this.updatedtime;
    }
    
    public void setUpdatedtime(Date updatedtime) {
        this.updatedtime = updatedtime;
    }

    
    @Column(name="SERVICE_CHARGE", length=45)
    public String getServiceCharge() {
        return this.serviceCharge;
    }
    
    public void setServiceCharge(String serviceCharge) {
        this.serviceCharge = serviceCharge;
    }

    
    @Column(name="REFNO", length=50)
    public String getRefno() {
        return this.refno;
    }
    
    public void setRefno(String refno) {
        this.refno = refno;
    }

    
    @Column(name="SCH_ID")
    public Integer getSchId() {
        return this.schId;
    }
    
    public void setSchId(Integer schId) {
        this.schId = schId;
    }

    
    @Column(name="HOLDER_NAME")
    public String getHolderName() {
        return this.holderName;
    }
    
    public void setHolderName(String holderName) {
        this.holderName = holderName;
    }

    
    @Column(name="TO_ACCOUNT")
    public String getToAccount() {
        return this.toAccount;
    }
    
    public void setToAccount(String toAccount) {
        this.toAccount = toAccount;
    }

    
    @Column(name="FROM_ACCOUNT")
    public String getFromAccount() {
        return this.fromAccount;
    }
    
    public void setFromAccount(String fromAccount) {
        this.fromAccount = fromAccount;
    }

    
    @Column(name="REG_ACCOUNT", length=1)
    public String getRegAccount() {
        return this.regAccount;
    }
    
    public void setRegAccount(String regAccount) {
        this.regAccount = regAccount;
    }

    
    @Column(name="CEFT_DESCRIPTION", length=256)
    public String getCeftDescription() {
        return this.ceftDescription;
    }
    
    public void setCeftDescription(String ceftDescription) {
        this.ceftDescription = ceftDescription;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="dlbSwtStTransaction")
    public DlbEzCashCheck getDlbEzCashCheck() {
        return this.dlbEzCashCheck;
    }
    
    public void setDlbEzCashCheck(DlbEzCashCheck dlbEzCashCheck) {
        this.dlbEzCashCheck = dlbEzCashCheck;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbSwtStTransaction")
    public Set<DlbSwtStTransactionHistory> getDlbSwtStTransactionHistories() {
        return this.dlbSwtStTransactionHistories;
    }
    
    public void setDlbSwtStTransactionHistories(Set<DlbSwtStTransactionHistory> dlbSwtStTransactionHistories) {
        this.dlbSwtStTransactionHistories = dlbSwtStTransactionHistories;
    }

    @Transient
    public String getReferenceNo() {
        return referenceNo;
    }

    public void setReferenceNo(String referenceNo) {
        this.referenceNo = referenceNo;
    }

    
     @Transient
    public String getBank() {
        return bank;
    }

    public void setBank(String bank) {
        this.bank = bank;
    }




}


