package com.epic.dlb.model;
// Generated Jun 15, 2018 2:03:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DlbStatusCategory generated by hbm2java
 */
@Entity
@Table(name="DLB_STATUS_CATEGORY"
    
)
public class DlbStatusCategory  implements java.io.Serializable {


     private String statuscategorycode;
     private String description;
     private String lastUpdatedUser;
     private Date lastUpdatedTime;
     private Date createdTime;
     private Set<DlbStatus> dlbStatuses = new HashSet<DlbStatus>(0);

    public DlbStatusCategory() {
    }

	
    public DlbStatusCategory(String statuscategorycode, String description) {
        this.statuscategorycode = statuscategorycode;
        this.description = description;
    }
    public DlbStatusCategory(String statuscategorycode, String description, String lastUpdatedUser, Date lastUpdatedTime, Date createdTime, Set<DlbStatus> dlbStatuses) {
       this.statuscategorycode = statuscategorycode;
       this.description = description;
       this.lastUpdatedUser = lastUpdatedUser;
       this.lastUpdatedTime = lastUpdatedTime;
       this.createdTime = createdTime;
       this.dlbStatuses = dlbStatuses;
    }
   
     @Id 

    
    @Column(name="STATUSCATEGORYCODE", unique=true, nullable=false, length=16)
    public String getStatuscategorycode() {
        return this.statuscategorycode;
    }
    
    public void setStatuscategorycode(String statuscategorycode) {
        this.statuscategorycode = statuscategorycode;
    }

    
    @Column(name="DESCRIPTION", nullable=false, length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="LAST_UPDATED_USER", length=128)
    public String getLastUpdatedUser() {
        return this.lastUpdatedUser;
    }
    
    public void setLastUpdatedUser(String lastUpdatedUser) {
        this.lastUpdatedUser = lastUpdatedUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED_TIME", length=19)
    public Date getLastUpdatedTime() {
        return this.lastUpdatedTime;
    }
    
    public void setLastUpdatedTime(Date lastUpdatedTime) {
        this.lastUpdatedTime = lastUpdatedTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_TIME", length=19)
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbStatusCategory")
    public Set<DlbStatus> getDlbStatuses() {
        return this.dlbStatuses;
    }
    
    public void setDlbStatuses(Set<DlbStatus> dlbStatuses) {
        this.dlbStatuses = dlbStatuses;
    }




}


