package com.epic.dlb.model;
// Generated Jun 15, 2018 2:03:02 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DlbSwtMtBank generated by hbm2java
 */
@Entity
@Table(name="DLB_SWT_MT_BANK"
    
)
public class DlbSwtMtBank  implements java.io.Serializable {


     private String bankCode;
     private String name;
     private String imgurl;

    public DlbSwtMtBank() {
    }

	
    public DlbSwtMtBank(String bankCode) {
        this.bankCode = bankCode;
    }
    public DlbSwtMtBank(String bankCode, String name, String imgurl) {
       this.bankCode = bankCode;
       this.name = name;
       this.imgurl = imgurl;
    }
   
     @Id 

    
    @Column(name="BANK_CODE", unique=true, nullable=false, length=4)
    public String getBankCode() {
        return this.bankCode;
    }
    
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode;
    }

    
    @Column(name="NAME", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="IMGURL")
    public String getImgurl() {
        return this.imgurl;
    }
    
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl;
    }




}


