package com.epic.dlb.model;
// Generated Jun 15, 2018 2:03:02 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * DlbSwtStWallet generated by hbm2java
 */
@Entity
@Table(name="DLB_SWT_ST_WALLET"
    
    , uniqueConstraints = {@UniqueConstraint(columnNames="MOBILE_NO"), @UniqueConstraint(columnNames="USERNAME")} 
)
public class DlbSwtStWallet  implements java.io.Serializable {


     private Integer id;
     private DlbStatus dlbStatusByStatus;
     private DlbStatus dlbStatusByAccstatus;
     private String uuid;
     private String model;
     private String brand;
     private String osVersion;
     private String osType;
     private String pushId;
     private String mobileNo;
     private String otp;
     private String mpin;
     private Integer attemptCount;
     private Date createTime;
     private Integer loginStatus;
     private Date lastLoginTime;
     private Date lastUpdatedTime;
     private String firstName;
     private String lastName;
     private String nic;
     private Integer request;
     private String username;
     private String profile;
     private byte[] nicfront;
     private byte[] nicback;
     private Integer traceno;
     private BigDecimal balance;
     private byte[] passport;
     private byte[] drivinglic;
     private String email;
     private Set<DlbSwtStPurchaseHistory> dlbSwtStPurchaseHistories = new HashSet<DlbSwtStPurchaseHistory>(0);
     private Set<DlbSwtStTransaction> dlbSwtStTransactions = new HashSet<DlbSwtStTransaction>(0);
     private Set<DlbWbTicket> dlbWbTickets = new HashSet<DlbWbTicket>(0);
     private Set<DlbSwtStToken> dlbSwtStTokens = new HashSet<DlbSwtStToken>(0);
     private Set<DlbSwtStWalletHistory> dlbSwtStWalletHistories = new HashSet<DlbSwtStWalletHistory>(0);

    public DlbSwtStWallet() {
    }

    public DlbSwtStWallet(Integer id) {
        this.id = id;
    }
	
    public DlbSwtStWallet(DlbStatus dlbStatusByStatus, DlbStatus dlbStatusByAccstatus, String mobileNo, Date createTime) {
        this.dlbStatusByStatus = dlbStatusByStatus;
        this.dlbStatusByAccstatus = dlbStatusByAccstatus;
        this.mobileNo = mobileNo;
        this.createTime = createTime;
    }
    public DlbSwtStWallet(DlbStatus dlbStatusByStatus, DlbStatus dlbStatusByAccstatus, String uuid, String model, String brand, String osVersion, String osType, String pushId, String mobileNo, String otp, String mpin, Integer attemptCount, Date createTime, Integer loginStatus, Date lastLoginTime, Date lastUpdatedTime, String firstName, String lastName, String nic, Integer request, String username, String profile, byte[] nicfront, byte[] nicback, Integer traceno, BigDecimal balance, byte[] passport, byte[] drivinglic, Set<DlbSwtStPurchaseHistory> dlbSwtStPurchaseHistories, Set<DlbSwtStTransaction> dlbSwtStTransactions, Set<DlbWbTicket> dlbWbTickets, Set<DlbSwtStToken> dlbSwtStTokens, Set<DlbSwtStWalletHistory> dlbSwtStWalletHistories) {
       this.dlbStatusByStatus = dlbStatusByStatus;
       this.dlbStatusByAccstatus = dlbStatusByAccstatus;
       this.uuid = uuid;
       this.model = model;
       this.brand = brand;
       this.osVersion = osVersion;
       this.osType = osType;
       this.pushId = pushId;
       this.mobileNo = mobileNo;
       this.otp = otp;
       this.mpin = mpin;
       this.attemptCount = attemptCount;
       this.createTime = createTime;
       this.loginStatus = loginStatus;
       this.lastLoginTime = lastLoginTime;
       this.lastUpdatedTime = lastUpdatedTime;
       this.firstName = firstName;
       this.lastName = lastName;
       this.nic = nic;
       this.request = request;
       this.username = username;
       this.profile = profile;
       this.nicfront = nicfront;
       this.nicback = nicback;
       this.traceno = traceno;
       this.balance = balance;
       this.passport = passport;
       this.drivinglic = drivinglic;
       this.dlbSwtStPurchaseHistories = dlbSwtStPurchaseHistories;
       this.dlbSwtStTransactions = dlbSwtStTransactions;
       this.dlbWbTickets = dlbWbTickets;
       this.dlbSwtStTokens = dlbSwtStTokens;
       this.dlbSwtStWalletHistories = dlbSwtStWalletHistories;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS", nullable=false)
    public DlbStatus getDlbStatusByStatus() {
        return this.dlbStatusByStatus;
    }
    
    public void setDlbStatusByStatus(DlbStatus dlbStatusByStatus) {
        this.dlbStatusByStatus = dlbStatusByStatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ACCSTATUS", nullable=false)
    public DlbStatus getDlbStatusByAccstatus() {
        return this.dlbStatusByAccstatus;
    }
    
    public void setDlbStatusByAccstatus(DlbStatus dlbStatusByAccstatus) {
        this.dlbStatusByAccstatus = dlbStatusByAccstatus;
    }

    
    @Column(name="UUID", length=100)
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    
    @Column(name="MODEL", length=50)
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }

    
    @Column(name="BRAND", length=50)
    public String getBrand() {
        return this.brand;
    }
    
    public void setBrand(String brand) {
        this.brand = brand;
    }

    
    @Column(name="OS_VERSION", length=50)
    public String getOsVersion() {
        return this.osVersion;
    }
    
    public void setOsVersion(String osVersion) {
        this.osVersion = osVersion;
    }

    
    @Column(name="OS_TYPE", length=50)
    public String getOsType() {
        return this.osType;
    }
    
    public void setOsType(String osType) {
        this.osType = osType;
    }

    
    @Column(name="PUSH_ID", length=200)
    public String getPushId() {
        return this.pushId;
    }
    
    public void setPushId(String pushId) {
        this.pushId = pushId;
    }

    
    @Column(name="MOBILE_NO", unique=true, nullable=false, length=15)
    public String getMobileNo() {
        return this.mobileNo;
    }
    
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }

    
    @Column(name="OTP", length=10)
    public String getOtp() {
        return this.otp;
    }
    
    public void setOtp(String otp) {
        this.otp = otp;
    }

    
    @Column(name="MPIN", length=160)
    public String getMpin() {
        return this.mpin;
    }
    
    public void setMpin(String mpin) {
        this.mpin = mpin;
    }

    
    @Column(name="ATTEMPT_COUNT")
    public Integer getAttemptCount() {
        return this.attemptCount;
    }
    
    public void setAttemptCount(Integer attemptCount) {
        this.attemptCount = attemptCount;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_TIME", nullable=false, length=19)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    
    @Column(name="LOGIN_STATUS")
    public Integer getLoginStatus() {
        return this.loginStatus;
    }
    
    public void setLoginStatus(Integer loginStatus) {
        this.loginStatus = loginStatus;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_LOGIN_TIME", length=19)
    public Date getLastLoginTime() {
        return this.lastLoginTime;
    }
    
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED_TIME", length=19)
    public Date getLastUpdatedTime() {
        return this.lastUpdatedTime;
    }
    
    public void setLastUpdatedTime(Date lastUpdatedTime) {
        this.lastUpdatedTime = lastUpdatedTime;
    }

    
    @Column(name="FIRST_NAME", length=50)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="LAST_NAME", length=50)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="NIC", length=15)
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }

    
    @Column(name="REQUEST")
    public Integer getRequest() {
        return this.request;
    }
    
    public void setRequest(Integer request) {
        this.request = request;
    }

    
    @Column(name="USERNAME", unique=true, length=100)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="Profile", length=500)
    public String getProfile() {
        return this.profile;
    }
    
    public void setProfile(String profile) {
        this.profile = profile;
    }

    
    @Column(name="NICFRONT")
    public byte[] getNicfront() {
        return this.nicfront;
    }
    
    public void setNicfront(byte[] nicfront) {
        this.nicfront = nicfront;
    }

    
    @Column(name="NICBACK")
    public byte[] getNicback() {
        return this.nicback;
    }
    
    public void setNicback(byte[] nicback) {
        this.nicback = nicback;
    }

    
    @Column(name="TRACENO")
    public Integer getTraceno() {
        return this.traceno;
    }
    
    public void setTraceno(Integer traceno) {
        this.traceno = traceno;
    }

    
    @Column(name="BALANCE", precision=10)
    public BigDecimal getBalance() {
        return this.balance;
    }
    
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    
    @Column(name="PASSPORT")
    public byte[] getPassport() {
        return this.passport;
    }
    
    public void setPassport(byte[] passport) {
        this.passport = passport;
    }

    
    @Column(name="DRIVINGLIC")
    public byte[] getDrivinglic() {
        return this.drivinglic;
    }
    
    public void setDrivinglic(byte[] drivinglic) {
        this.drivinglic = drivinglic;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbSwtStWallet")
    public Set<DlbSwtStPurchaseHistory> getDlbSwtStPurchaseHistories() {
        return this.dlbSwtStPurchaseHistories;
    }
    
    public void setDlbSwtStPurchaseHistories(Set<DlbSwtStPurchaseHistory> dlbSwtStPurchaseHistories) {
        this.dlbSwtStPurchaseHistories = dlbSwtStPurchaseHistories;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbSwtStWallet")
    public Set<DlbSwtStTransaction> getDlbSwtStTransactions() {
        return this.dlbSwtStTransactions;
    }
    
    public void setDlbSwtStTransactions(Set<DlbSwtStTransaction> dlbSwtStTransactions) {
        this.dlbSwtStTransactions = dlbSwtStTransactions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbSwtStWallet")
    public Set<DlbWbTicket> getDlbWbTickets() {
        return this.dlbWbTickets;
    }
    
    public void setDlbWbTickets(Set<DlbWbTicket> dlbWbTickets) {
        this.dlbWbTickets = dlbWbTickets;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbSwtStWallet")
    public Set<DlbSwtStToken> getDlbSwtStTokens() {
        return this.dlbSwtStTokens;
    }
    
    public void setDlbSwtStTokens(Set<DlbSwtStToken> dlbSwtStTokens) {
        this.dlbSwtStTokens = dlbSwtStTokens;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbSwtStWallet")
    public Set<DlbSwtStWalletHistory> getDlbSwtStWalletHistories() {
        return this.dlbSwtStWalletHistories;
    }
    
    public void setDlbSwtStWalletHistories(Set<DlbSwtStWalletHistory> dlbSwtStWalletHistories) {
        this.dlbSwtStWalletHistories = dlbSwtStWalletHistories;
    }

    @Column(name="EMAIL")
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }




}


