package com.epic.dlb.model;
// Generated Jun 15, 2018 2:03:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * DlbSwtStTransactionHistory generated by hbm2java
 */
@Entity
@Table(name="DLB_SWT_ST_TRANSACTION_HISTORY"
    
)
public class DlbSwtStTransactionHistory  implements java.io.Serializable {


     private DlbSwtStTransactionHistoryId id;
     private Date timestamp;
     private DlbStatus dlbStatus;
     private DlbSwtStTransaction dlbSwtStTransaction;

    public DlbSwtStTransactionHistory() {
    }

    public DlbSwtStTransactionHistory(DlbSwtStTransactionHistoryId id, DlbStatus dlbStatus, DlbSwtStTransaction dlbSwtStTransaction) {
       this.id = id;
       this.dlbStatus = dlbStatus;
       this.dlbSwtStTransaction = dlbSwtStTransaction;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="txnid", column=@Column(name="TXNID", nullable=false, length=32) ), 
        @AttributeOverride(name="status", column=@Column(name="STATUS", nullable=false) ) } )
    public DlbSwtStTransactionHistoryId getId() {
        return this.id;
    }
    
    public void setId(DlbSwtStTransactionHistoryId id) {
        this.id = id;
    }

    @Version@Temporal(TemporalType.TIMESTAMP)
    @Column(name="TIMESTAMP", nullable=false, length=19)
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS", nullable=false, insertable=false, updatable=false)
    public DlbStatus getDlbStatus() {
        return this.dlbStatus;
    }
    
    public void setDlbStatus(DlbStatus dlbStatus) {
        this.dlbStatus = dlbStatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TXNID", nullable=false, insertable=false, updatable=false)
    public DlbSwtStTransaction getDlbSwtStTransaction() {
        return this.dlbSwtStTransaction;
    }
    
    public void setDlbSwtStTransaction(DlbSwtStTransaction dlbSwtStTransaction) {
        this.dlbSwtStTransaction = dlbSwtStTransaction;
    }




}


