package com.epic.dlb.model;
// Generated Jun 15, 2018 2:03:02 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DlbSwtStServiceCharge generated by hbm2java
 */
@Entity
@Table(name="DLB_SWT_ST_SERVICE_CHARGE"
    
)
public class DlbSwtStServiceCharge  implements java.io.Serializable {


     private Integer id;
     private DlbSwtMtTxnType dlbSwtMtTxnType;
     private String desc;
     private BigDecimal bankCharge;
     private BigDecimal lankapayCharge;
     private BigDecimal ctlCharge;

    public DlbSwtStServiceCharge() {
    }

    public DlbSwtStServiceCharge(DlbSwtMtTxnType dlbSwtMtTxnType, String desc, BigDecimal bankCharge, BigDecimal lankapayCharge, BigDecimal ctlCharge) {
       this.dlbSwtMtTxnType = dlbSwtMtTxnType;
       this.desc = desc;
       this.bankCharge = bankCharge;
       this.lankapayCharge = lankapayCharge;
       this.ctlCharge = ctlCharge;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TXN_TYPE")
    public DlbSwtMtTxnType getDlbSwtMtTxnType() {
        return this.dlbSwtMtTxnType;
    }
    
    public void setDlbSwtMtTxnType(DlbSwtMtTxnType dlbSwtMtTxnType) {
        this.dlbSwtMtTxnType = dlbSwtMtTxnType;
    }

    
    @Column(name="DESC", length=100)
    public String getDesc() {
        return this.desc;
    }
    
    public void setDesc(String desc) {
        this.desc = desc;
    }

    
    @Column(name="BANK_CHARGE", precision=5)
    public BigDecimal getBankCharge() {
        return this.bankCharge;
    }
    
    public void setBankCharge(BigDecimal bankCharge) {
        this.bankCharge = bankCharge;
    }

    
    @Column(name="LANKAPAY_CHARGE", precision=5)
    public BigDecimal getLankapayCharge() {
        return this.lankapayCharge;
    }
    
    public void setLankapayCharge(BigDecimal lankapayCharge) {
        this.lankapayCharge = lankapayCharge;
    }

    
    @Column(name="CTL_CHARGE", precision=5)
    public BigDecimal getCtlCharge() {
        return this.ctlCharge;
    }
    
    public void setCtlCharge(BigDecimal ctlCharge) {
        this.ctlCharge = ctlCharge;
    }




}


