package com.epic.dlb.model;
// Generated Jun 15, 2018 2:03:02 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DlbSwtMtResponseCode generated by hbm2java
 */
@Entity
@Table(name="DLB_SWT_MT_RESPONSE_CODE"
    
)
public class DlbSwtMtResponseCode  implements java.io.Serializable {


     private String code;
     private String description;

    public DlbSwtMtResponseCode() {
    }

    public DlbSwtMtResponseCode(String code, String description) {
       this.code = code;
       this.description = description;
    }
   
     @Id 

    
    @Column(name="CODE", unique=true, nullable=false, length=4)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="DESCRIPTION", nullable=false, length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


