package com.epic.dlb.model;
// Generated Jun 15, 2018 2:03:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DlbSwtMtMessageTemplateType generated by hbm2java
 */
@Entity
@Table(name="DLB_SWT_MT_MESSAGE_TEMPLATE_TYPE"
    
)
public class DlbSwtMtMessageTemplateType  implements java.io.Serializable {


     private String code;
     private DlbSwtMtMessageTemplateCategory dlbSwtMtMessageTemplateCategory;
     private String description;
     private Set<DlbSwtStMessageTemplate> dlbSwtStMessageTemplates = new HashSet<DlbSwtStMessageTemplate>(0);

    public DlbSwtMtMessageTemplateType() {
    }

	
    public DlbSwtMtMessageTemplateType(String code) {
        this.code = code;
    }
    public DlbSwtMtMessageTemplateType(String code, DlbSwtMtMessageTemplateCategory dlbSwtMtMessageTemplateCategory, String description, Set<DlbSwtStMessageTemplate> dlbSwtStMessageTemplates) {
       this.code = code;
       this.dlbSwtMtMessageTemplateCategory = dlbSwtMtMessageTemplateCategory;
       this.description = description;
       this.dlbSwtStMessageTemplates = dlbSwtStMessageTemplates;
    }
   
     @Id 

    
    @Column(name="CODE", unique=true, nullable=false, length=30)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TEMPLATE_CATEGORY_CODE")
    public DlbSwtMtMessageTemplateCategory getDlbSwtMtMessageTemplateCategory() {
        return this.dlbSwtMtMessageTemplateCategory;
    }
    
    public void setDlbSwtMtMessageTemplateCategory(DlbSwtMtMessageTemplateCategory dlbSwtMtMessageTemplateCategory) {
        this.dlbSwtMtMessageTemplateCategory = dlbSwtMtMessageTemplateCategory;
    }

    
    @Column(name="DESCRIPTION", length=500)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbSwtMtMessageTemplateType")
    public Set<DlbSwtStMessageTemplate> getDlbSwtStMessageTemplates() {
        return this.dlbSwtStMessageTemplates;
    }
    
    public void setDlbSwtStMessageTemplates(Set<DlbSwtStMessageTemplate> dlbSwtStMessageTemplates) {
        this.dlbSwtStMessageTemplates = dlbSwtStMessageTemplates;
    }




}


