package com.epic.dlb.model;
// Generated Jun 15, 2018 2:03:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DlbStatus generated by hbm2java
 */
@Entity
@Table(name="DLB_STATUS"
    
)
public class DlbStatus  implements java.io.Serializable {


     private int statusCode;
     private DlbStatusCategory dlbStatusCategory;
     private String description;
     private String lastUpdatedUser;
     private Date lastUpdatedTime;
     private Date createdTime;
     private Set<DlbWbPromotion> dlbWbPromotions = new HashSet<DlbWbPromotion>(0);
     private Set<DlbWbResult> dlbWbResults = new HashSet<DlbWbResult>(0);
     private Set<DlbSwtStWallet> dlbSwtStWalletsForStatus = new HashSet<DlbSwtStWallet>(0);
     private Set<DlbWbWiningFileHistory> dlbWbWiningFileHistories = new HashSet<DlbWbWiningFileHistory>(0);
     private Set<DlbWbSubSection> dlbWbSubSections = new HashSet<DlbWbSubSection>(0);
     private Set<DlbDeviceProfile> dlbDeviceProfiles = new HashSet<DlbDeviceProfile>(0);
     private Set<DlbSwtStPurchaseHistory> dlbSwtStPurchaseHistoriesForStatus = new HashSet<DlbSwtStPurchaseHistory>(0);
     private Set<DlbWbProduct> dlbWbProducts = new HashSet<DlbWbProduct>(0);
     private Set<DlbWbProductProfile> dlbWbProductProfilesForStatus = new HashSet<DlbWbProductProfile>(0);
     private Set<DlbSwtMtConfiguration> dlbSwtMtConfigurationsForStatus = new HashSet<DlbSwtMtConfiguration>(0);
     private Set<DlbWbWiningFile> dlbWbWiningFiles = new HashSet<DlbWbWiningFile>(0);
     private Set<DlbSwtMtConfiguration> dlbSwtMtConfigurationsForLogBackupStatus = new HashSet<DlbSwtMtConfiguration>(0);
     private Set<DlbWbPage> dlbWbPages = new HashSet<DlbWbPage>(0);
     private Set<DlbSwtStTransaction> dlbSwtStTransactions = new HashSet<DlbSwtStTransaction>(0);
     private Set<DlbWbWeekDay> dlbWbWeekDays = new HashSet<DlbWbWeekDay>(0);
     private Set<DlbWbUserRoleCategory> dlbWbUserRoleCategories = new HashSet<DlbWbUserRoleCategory>(0);
     private Set<DlbSwtStTransactionHistory> dlbSwtStTransactionHistories = new HashSet<DlbSwtStTransactionHistory>(0);
     private Set<DlbWbWiningFileApprovalHistory> dlbWbWiningFileApprovalHistories = new HashSet<DlbWbWiningFileApprovalHistory>(0);
     private Set<DlbWbEmployee> dlbWbEmployees = new HashSet<DlbWbEmployee>(0);
     private Set<DlbWbProductProfile> dlbWbProductProfilesForSpecialStatus = new HashSet<DlbWbProductProfile>(0);
     private Set<DlbWbRiskProfile> dlbWbRiskProfiles = new HashSet<DlbWbRiskProfile>(0);
     private Set<DlbWbAuthorizedDevice> dlbWbAuthorizedDevices = new HashSet<DlbWbAuthorizedDevice>(0);
     private Set<DlbWbTicketFile> dlbWbTicketFiles = new HashSet<DlbWbTicketFile>(0);
     private Set<DlbWbUserRole> dlbWbUserRoles = new HashSet<DlbWbUserRole>(0);
     private Set<DlbSwtStPurchaseHistory> dlbSwtStPurchaseHistoriesForNotifyStatus = new HashSet<DlbSwtStPurchaseHistory>(0);
     private Set<DlbSwtStWallet> dlbSwtStWalletsForAccstatus = new HashSet<DlbSwtStWallet>(0);
     private Set<DlbSwtStToken> dlbSwtStTokens = new HashSet<DlbSwtStToken>(0);
     private Set<DlbWbSystemUser> dlbWbSystemUsers = new HashSet<DlbWbSystemUser>(0);
     private Set<DlbWbProductItem> dlbWbProductItems = new HashSet<DlbWbProductItem>(0);
     private Set<DlbWbProductList> dlbWbProductLists = new HashSet<DlbWbProductList>(0);
     private Set<DlbWbSection> dlbWbSections = new HashSet<DlbWbSection>(0);

    public DlbStatus() {
    }

      public DlbStatus(int statusCode) {
        this.statusCode = statusCode;
    }
	
    public DlbStatus(int statusCode, DlbStatusCategory dlbStatusCategory, String description) {
        this.statusCode = statusCode;
        this.dlbStatusCategory = dlbStatusCategory;
        this.description = description;
    }
    public DlbStatus(int statusCode, DlbStatusCategory dlbStatusCategory, String description, String lastUpdatedUser, Date lastUpdatedTime, Date createdTime, Set<DlbWbPromotion> dlbWbPromotions, Set<DlbWbResult> dlbWbResults, Set<DlbSwtStWallet> dlbSwtStWalletsForStatus, Set<DlbWbWiningFileHistory> dlbWbWiningFileHistories, Set<DlbWbSubSection> dlbWbSubSections, Set<DlbDeviceProfile> dlbDeviceProfiles, Set<DlbSwtStPurchaseHistory> dlbSwtStPurchaseHistoriesForStatus, Set<DlbWbProduct> dlbWbProducts, Set<DlbWbProductProfile> dlbWbProductProfilesForStatus, Set<DlbSwtMtConfiguration> dlbSwtMtConfigurationsForStatus, Set<DlbWbWiningFile> dlbWbWiningFiles, Set<DlbSwtMtConfiguration> dlbSwtMtConfigurationsForLogBackupStatus, Set<DlbWbPage> dlbWbPages, Set<DlbSwtStTransaction> dlbSwtStTransactions, Set<DlbWbWeekDay> dlbWbWeekDays, Set<DlbWbUserRoleCategory> dlbWbUserRoleCategories, Set<DlbSwtStTransactionHistory> dlbSwtStTransactionHistories, Set<DlbWbWiningFileApprovalHistory> dlbWbWiningFileApprovalHistories, Set<DlbWbEmployee> dlbWbEmployees, Set<DlbWbProductProfile> dlbWbProductProfilesForSpecialStatus, Set<DlbWbRiskProfile> dlbWbRiskProfiles, Set<DlbWbAuthorizedDevice> dlbWbAuthorizedDevices, Set<DlbWbTicketFile> dlbWbTicketFiles, Set<DlbWbUserRole> dlbWbUserRoles, Set<DlbSwtStPurchaseHistory> dlbSwtStPurchaseHistoriesForNotifyStatus, Set<DlbSwtStWallet> dlbSwtStWalletsForAccstatus, Set<DlbSwtStToken> dlbSwtStTokens, Set<DlbWbSystemUser> dlbWbSystemUsers, Set<DlbWbProductItem> dlbWbProductItems, Set<DlbWbProductList> dlbWbProductLists, Set<DlbWbSection> dlbWbSections) {
       this.statusCode = statusCode;
       this.dlbStatusCategory = dlbStatusCategory;
       this.description = description;
       this.lastUpdatedUser = lastUpdatedUser;
       this.lastUpdatedTime = lastUpdatedTime;
       this.createdTime = createdTime;
       this.dlbWbPromotions = dlbWbPromotions;
       this.dlbWbResults = dlbWbResults;
       this.dlbSwtStWalletsForStatus = dlbSwtStWalletsForStatus;
       this.dlbWbWiningFileHistories = dlbWbWiningFileHistories;
       this.dlbWbSubSections = dlbWbSubSections;
       this.dlbDeviceProfiles = dlbDeviceProfiles;
       this.dlbSwtStPurchaseHistoriesForStatus = dlbSwtStPurchaseHistoriesForStatus;
       this.dlbWbProducts = dlbWbProducts;
       this.dlbWbProductProfilesForStatus = dlbWbProductProfilesForStatus;
       this.dlbSwtMtConfigurationsForStatus = dlbSwtMtConfigurationsForStatus;
       this.dlbWbWiningFiles = dlbWbWiningFiles;
       this.dlbSwtMtConfigurationsForLogBackupStatus = dlbSwtMtConfigurationsForLogBackupStatus;
       this.dlbWbPages = dlbWbPages;
       this.dlbSwtStTransactions = dlbSwtStTransactions;
       this.dlbWbWeekDays = dlbWbWeekDays;
       this.dlbWbUserRoleCategories = dlbWbUserRoleCategories;
       this.dlbSwtStTransactionHistories = dlbSwtStTransactionHistories;
       this.dlbWbWiningFileApprovalHistories = dlbWbWiningFileApprovalHistories;
       this.dlbWbEmployees = dlbWbEmployees;
       this.dlbWbProductProfilesForSpecialStatus = dlbWbProductProfilesForSpecialStatus;
       this.dlbWbRiskProfiles = dlbWbRiskProfiles;
       this.dlbWbAuthorizedDevices = dlbWbAuthorizedDevices;
       this.dlbWbTicketFiles = dlbWbTicketFiles;
       this.dlbWbUserRoles = dlbWbUserRoles;
       this.dlbSwtStPurchaseHistoriesForNotifyStatus = dlbSwtStPurchaseHistoriesForNotifyStatus;
       this.dlbSwtStWalletsForAccstatus = dlbSwtStWalletsForAccstatus;
       this.dlbSwtStTokens = dlbSwtStTokens;
       this.dlbWbSystemUsers = dlbWbSystemUsers;
       this.dlbWbProductItems = dlbWbProductItems;
       this.dlbWbProductLists = dlbWbProductLists;
       this.dlbWbSections = dlbWbSections;
    }
   
     @Id 

    
    @Column(name="STATUS_CODE", unique=true, nullable=false)
    public int getStatusCode() {
        return this.statusCode;
    }
    
    public void setStatusCode(int statusCode) {
        this.statusCode = statusCode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS_CATEGORY", nullable=false)
    public DlbStatusCategory getDlbStatusCategory() {
        return this.dlbStatusCategory;
    }
    
    public void setDlbStatusCategory(DlbStatusCategory dlbStatusCategory) {
        this.dlbStatusCategory = dlbStatusCategory;
    }

    
    @Column(name="DESCRIPTION", nullable=false, length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="LAST_UPDATED_USER", length=128)
    public String getLastUpdatedUser() {
        return this.lastUpdatedUser;
    }
    
    public void setLastUpdatedUser(String lastUpdatedUser) {
        this.lastUpdatedUser = lastUpdatedUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED_TIME", length=19)
    public Date getLastUpdatedTime() {
        return this.lastUpdatedTime;
    }
    
    public void setLastUpdatedTime(Date lastUpdatedTime) {
        this.lastUpdatedTime = lastUpdatedTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_TIME", length=19)
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbStatus")
    public Set<DlbWbPromotion> getDlbWbPromotions() {
        return this.dlbWbPromotions;
    }
    
    public void setDlbWbPromotions(Set<DlbWbPromotion> dlbWbPromotions) {
        this.dlbWbPromotions = dlbWbPromotions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbStatus")
    public Set<DlbWbResult> getDlbWbResults() {
        return this.dlbWbResults;
    }
    
    public void setDlbWbResults(Set<DlbWbResult> dlbWbResults) {
        this.dlbWbResults = dlbWbResults;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbStatusByStatus")
    public Set<DlbSwtStWallet> getDlbSwtStWalletsForStatus() {
        return this.dlbSwtStWalletsForStatus;
    }
    
    public void setDlbSwtStWalletsForStatus(Set<DlbSwtStWallet> dlbSwtStWalletsForStatus) {
        this.dlbSwtStWalletsForStatus = dlbSwtStWalletsForStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbStatus")
    public Set<DlbWbWiningFileHistory> getDlbWbWiningFileHistories() {
        return this.dlbWbWiningFileHistories;
    }
    
    public void setDlbWbWiningFileHistories(Set<DlbWbWiningFileHistory> dlbWbWiningFileHistories) {
        this.dlbWbWiningFileHistories = dlbWbWiningFileHistories;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbStatus")
    public Set<DlbWbSubSection> getDlbWbSubSections() {
        return this.dlbWbSubSections;
    }
    
    public void setDlbWbSubSections(Set<DlbWbSubSection> dlbWbSubSections) {
        this.dlbWbSubSections = dlbWbSubSections;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbStatus")
    public Set<DlbDeviceProfile> getDlbDeviceProfiles() {
        return this.dlbDeviceProfiles;
    }
    
    public void setDlbDeviceProfiles(Set<DlbDeviceProfile> dlbDeviceProfiles) {
        this.dlbDeviceProfiles = dlbDeviceProfiles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbStatusByStatus")
    public Set<DlbSwtStPurchaseHistory> getDlbSwtStPurchaseHistoriesForStatus() {
        return this.dlbSwtStPurchaseHistoriesForStatus;
    }
    
    public void setDlbSwtStPurchaseHistoriesForStatus(Set<DlbSwtStPurchaseHistory> dlbSwtStPurchaseHistoriesForStatus) {
        this.dlbSwtStPurchaseHistoriesForStatus = dlbSwtStPurchaseHistoriesForStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbStatus")
    public Set<DlbWbProduct> getDlbWbProducts() {
        return this.dlbWbProducts;
    }
    
    public void setDlbWbProducts(Set<DlbWbProduct> dlbWbProducts) {
        this.dlbWbProducts = dlbWbProducts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbStatusByStatus")
    public Set<DlbWbProductProfile> getDlbWbProductProfilesForStatus() {
        return this.dlbWbProductProfilesForStatus;
    }
    
    public void setDlbWbProductProfilesForStatus(Set<DlbWbProductProfile> dlbWbProductProfilesForStatus) {
        this.dlbWbProductProfilesForStatus = dlbWbProductProfilesForStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbStatusByStatus")
    public Set<DlbSwtMtConfiguration> getDlbSwtMtConfigurationsForStatus() {
        return this.dlbSwtMtConfigurationsForStatus;
    }
    
    public void setDlbSwtMtConfigurationsForStatus(Set<DlbSwtMtConfiguration> dlbSwtMtConfigurationsForStatus) {
        this.dlbSwtMtConfigurationsForStatus = dlbSwtMtConfigurationsForStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbStatus")
    public Set<DlbWbWiningFile> getDlbWbWiningFiles() {
        return this.dlbWbWiningFiles;
    }
    
    public void setDlbWbWiningFiles(Set<DlbWbWiningFile> dlbWbWiningFiles) {
        this.dlbWbWiningFiles = dlbWbWiningFiles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbStatusByLogBackupStatus")
    public Set<DlbSwtMtConfiguration> getDlbSwtMtConfigurationsForLogBackupStatus() {
        return this.dlbSwtMtConfigurationsForLogBackupStatus;
    }
    
    public void setDlbSwtMtConfigurationsForLogBackupStatus(Set<DlbSwtMtConfiguration> dlbSwtMtConfigurationsForLogBackupStatus) {
        this.dlbSwtMtConfigurationsForLogBackupStatus = dlbSwtMtConfigurationsForLogBackupStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbStatus")
    public Set<DlbWbPage> getDlbWbPages() {
        return this.dlbWbPages;
    }
    
    public void setDlbWbPages(Set<DlbWbPage> dlbWbPages) {
        this.dlbWbPages = dlbWbPages;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbStatus")
    public Set<DlbSwtStTransaction> getDlbSwtStTransactions() {
        return this.dlbSwtStTransactions;
    }
    
    public void setDlbSwtStTransactions(Set<DlbSwtStTransaction> dlbSwtStTransactions) {
        this.dlbSwtStTransactions = dlbSwtStTransactions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbStatus")
    public Set<DlbWbWeekDay> getDlbWbWeekDays() {
        return this.dlbWbWeekDays;
    }
    
    public void setDlbWbWeekDays(Set<DlbWbWeekDay> dlbWbWeekDays) {
        this.dlbWbWeekDays = dlbWbWeekDays;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbStatus")
    public Set<DlbWbUserRoleCategory> getDlbWbUserRoleCategories() {
        return this.dlbWbUserRoleCategories;
    }
    
    public void setDlbWbUserRoleCategories(Set<DlbWbUserRoleCategory> dlbWbUserRoleCategories) {
        this.dlbWbUserRoleCategories = dlbWbUserRoleCategories;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbStatus")
    public Set<DlbSwtStTransactionHistory> getDlbSwtStTransactionHistories() {
        return this.dlbSwtStTransactionHistories;
    }
    
    public void setDlbSwtStTransactionHistories(Set<DlbSwtStTransactionHistory> dlbSwtStTransactionHistories) {
        this.dlbSwtStTransactionHistories = dlbSwtStTransactionHistories;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbStatus")
    public Set<DlbWbWiningFileApprovalHistory> getDlbWbWiningFileApprovalHistories() {
        return this.dlbWbWiningFileApprovalHistories;
    }
    
    public void setDlbWbWiningFileApprovalHistories(Set<DlbWbWiningFileApprovalHistory> dlbWbWiningFileApprovalHistories) {
        this.dlbWbWiningFileApprovalHistories = dlbWbWiningFileApprovalHistories;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbStatus")
    public Set<DlbWbEmployee> getDlbWbEmployees() {
        return this.dlbWbEmployees;
    }
    
    public void setDlbWbEmployees(Set<DlbWbEmployee> dlbWbEmployees) {
        this.dlbWbEmployees = dlbWbEmployees;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbStatusBySpecialStatus")
    public Set<DlbWbProductProfile> getDlbWbProductProfilesForSpecialStatus() {
        return this.dlbWbProductProfilesForSpecialStatus;
    }
    
    public void setDlbWbProductProfilesForSpecialStatus(Set<DlbWbProductProfile> dlbWbProductProfilesForSpecialStatus) {
        this.dlbWbProductProfilesForSpecialStatus = dlbWbProductProfilesForSpecialStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbStatus")
    public Set<DlbWbRiskProfile> getDlbWbRiskProfiles() {
        return this.dlbWbRiskProfiles;
    }
    
    public void setDlbWbRiskProfiles(Set<DlbWbRiskProfile> dlbWbRiskProfiles) {
        this.dlbWbRiskProfiles = dlbWbRiskProfiles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbStatus")
    public Set<DlbWbAuthorizedDevice> getDlbWbAuthorizedDevices() {
        return this.dlbWbAuthorizedDevices;
    }
    
    public void setDlbWbAuthorizedDevices(Set<DlbWbAuthorizedDevice> dlbWbAuthorizedDevices) {
        this.dlbWbAuthorizedDevices = dlbWbAuthorizedDevices;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbStatus")
    public Set<DlbWbTicketFile> getDlbWbTicketFiles() {
        return this.dlbWbTicketFiles;
    }
    
    public void setDlbWbTicketFiles(Set<DlbWbTicketFile> dlbWbTicketFiles) {
        this.dlbWbTicketFiles = dlbWbTicketFiles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbStatus")
    public Set<DlbWbUserRole> getDlbWbUserRoles() {
        return this.dlbWbUserRoles;
    }
    
    public void setDlbWbUserRoles(Set<DlbWbUserRole> dlbWbUserRoles) {
        this.dlbWbUserRoles = dlbWbUserRoles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbStatusByNotifyStatus")
    public Set<DlbSwtStPurchaseHistory> getDlbSwtStPurchaseHistoriesForNotifyStatus() {
        return this.dlbSwtStPurchaseHistoriesForNotifyStatus;
    }
    
    public void setDlbSwtStPurchaseHistoriesForNotifyStatus(Set<DlbSwtStPurchaseHistory> dlbSwtStPurchaseHistoriesForNotifyStatus) {
        this.dlbSwtStPurchaseHistoriesForNotifyStatus = dlbSwtStPurchaseHistoriesForNotifyStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbStatusByAccstatus")
    public Set<DlbSwtStWallet> getDlbSwtStWalletsForAccstatus() {
        return this.dlbSwtStWalletsForAccstatus;
    }
    
    public void setDlbSwtStWalletsForAccstatus(Set<DlbSwtStWallet> dlbSwtStWalletsForAccstatus) {
        this.dlbSwtStWalletsForAccstatus = dlbSwtStWalletsForAccstatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbStatus")
    public Set<DlbSwtStToken> getDlbSwtStTokens() {
        return this.dlbSwtStTokens;
    }
    
    public void setDlbSwtStTokens(Set<DlbSwtStToken> dlbSwtStTokens) {
        this.dlbSwtStTokens = dlbSwtStTokens;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbStatus")
    public Set<DlbWbSystemUser> getDlbWbSystemUsers() {
        return this.dlbWbSystemUsers;
    }
    
    public void setDlbWbSystemUsers(Set<DlbWbSystemUser> dlbWbSystemUsers) {
        this.dlbWbSystemUsers = dlbWbSystemUsers;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbStatus")
    public Set<DlbWbProductItem> getDlbWbProductItems() {
        return this.dlbWbProductItems;
    }
    
    public void setDlbWbProductItems(Set<DlbWbProductItem> dlbWbProductItems) {
        this.dlbWbProductItems = dlbWbProductItems;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbStatus")
    public Set<DlbWbProductList> getDlbWbProductLists() {
        return this.dlbWbProductLists;
    }
    
    public void setDlbWbProductLists(Set<DlbWbProductList> dlbWbProductLists) {
        this.dlbWbProductLists = dlbWbProductLists;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbStatus")
    public Set<DlbWbSection> getDlbWbSections() {
        return this.dlbWbSections;
    }
    
    public void setDlbWbSections(Set<DlbWbSection> dlbWbSections) {
        this.dlbWbSections = dlbWbSections;
    }




}


