package com.epic.dlb.model;
// Generated Jun 15, 2018 2:03:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DlbSwtStToken generated by hbm2java
 */
@Entity
@Table(name="DLB_SWT_ST_TOKEN"
    
)
public class DlbSwtStToken  implements java.io.Serializable {


     private String token;
     private DlbStatus dlbStatus;
     private DlbSwtMtCardAssociationType dlbSwtMtCardAssociationType;
     private DlbSwtMtPaymentInstrument dlbSwtMtPaymentInstrument;
     private DlbSwtStWallet dlbSwtStWallet;
     private String bankCode;
     private String maskedNumber;
     private Date createdDate;
     private Date lastUpdated;
     private String nickName;

    public DlbSwtStToken() {
    }

	
    public DlbSwtStToken(String token) {
        this.token = token;
    }
    public DlbSwtStToken(String token, DlbStatus dlbStatus, DlbSwtMtCardAssociationType dlbSwtMtCardAssociationType, DlbSwtMtPaymentInstrument dlbSwtMtPaymentInstrument, DlbSwtStWallet dlbSwtStWallet, String bankCode, String maskedNumber, Date createdDate, Date lastUpdated, String nickName) {
       this.token = token;
       this.dlbStatus = dlbStatus;
       this.dlbSwtMtCardAssociationType = dlbSwtMtCardAssociationType;
       this.dlbSwtMtPaymentInstrument = dlbSwtMtPaymentInstrument;
       this.dlbSwtStWallet = dlbSwtStWallet;
       this.bankCode = bankCode;
       this.maskedNumber = maskedNumber;
       this.createdDate = createdDate;
       this.lastUpdated = lastUpdated;
       this.nickName = nickName;
    }
   
     @Id 

    
    @Column(name="TOKEN", unique=true, nullable=false, length=45)
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS")
    public DlbStatus getDlbStatus() {
        return this.dlbStatus;
    }
    
    public void setDlbStatus(DlbStatus dlbStatus) {
        this.dlbStatus = dlbStatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CARD_ASSOCIATION_TYPE")
    public DlbSwtMtCardAssociationType getDlbSwtMtCardAssociationType() {
        return this.dlbSwtMtCardAssociationType;
    }
    
    public void setDlbSwtMtCardAssociationType(DlbSwtMtCardAssociationType dlbSwtMtCardAssociationType) {
        this.dlbSwtMtCardAssociationType = dlbSwtMtCardAssociationType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PAYMENT_INSTRUMENT")
    public DlbSwtMtPaymentInstrument getDlbSwtMtPaymentInstrument() {
        return this.dlbSwtMtPaymentInstrument;
    }
    
    public void setDlbSwtMtPaymentInstrument(DlbSwtMtPaymentInstrument dlbSwtMtPaymentInstrument) {
        this.dlbSwtMtPaymentInstrument = dlbSwtMtPaymentInstrument;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="WALLET_ID")
    public DlbSwtStWallet getDlbSwtStWallet() {
        return this.dlbSwtStWallet;
    }
    
    public void setDlbSwtStWallet(DlbSwtStWallet dlbSwtStWallet) {
        this.dlbSwtStWallet = dlbSwtStWallet;
    }

    
    @Column(name="BANK_CODE", length=45)
    public String getBankCode() {
        return this.bankCode;
    }
    
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode;
    }

    
    @Column(name="MASKED_NUMBER", length=15)
    public String getMaskedNumber() {
        return this.maskedNumber;
    }
    
    public void setMaskedNumber(String maskedNumber) {
        this.maskedNumber = maskedNumber;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED", length=19)
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    
    @Column(name="NICK_NAME")
    public String getNickName() {
        return this.nickName;
    }
    
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }




}


