package com.epic.dlb.model;
// Generated Jun 15, 2018 2:03:02 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DlbSwtStMessageTemplate generated by hbm2java
 */
@Entity
@Table(name="DLB_SWT_ST_MESSAGE_TEMPLATE"
    
)
public class DlbSwtStMessageTemplate  implements java.io.Serializable {


     private Integer id;
     private DlbSwtMtMessageTemplateType dlbSwtMtMessageTemplateType;
     private String template;

    public DlbSwtStMessageTemplate() {
    }

    public DlbSwtStMessageTemplate(DlbSwtMtMessageTemplateType dlbSwtMtMessageTemplateType, String template) {
       this.dlbSwtMtMessageTemplateType = dlbSwtMtMessageTemplateType;
       this.template = template;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CODE")
    public DlbSwtMtMessageTemplateType getDlbSwtMtMessageTemplateType() {
        return this.dlbSwtMtMessageTemplateType;
    }
    
    public void setDlbSwtMtMessageTemplateType(DlbSwtMtMessageTemplateType dlbSwtMtMessageTemplateType) {
        this.dlbSwtMtMessageTemplateType = dlbSwtMtMessageTemplateType;
    }

    
    @Column(name="TEMPLATE", length=2000)
    public String getTemplate() {
        return this.template;
    }
    
    public void setTemplate(String template) {
        this.template = template;
    }




}


