package com.epic.dlb.model;
// Generated Jun 15, 2018 2:03:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DlbSwtMtMessageTemplateCategory generated by hbm2java
 */
@Entity
@Table(name="DLB_SWT_MT_MESSAGE_TEMPLATE_CATEGORY"
    
)
public class DlbSwtMtMessageTemplateCategory  implements java.io.Serializable {


     private int code;
     private String description;
     private Set<DlbSwtMtMessageTemplateType> dlbSwtMtMessageTemplateTypes = new HashSet<DlbSwtMtMessageTemplateType>(0);

    public DlbSwtMtMessageTemplateCategory() {
    }

	
    public DlbSwtMtMessageTemplateCategory(int code) {
        this.code = code;
    }
    public DlbSwtMtMessageTemplateCategory(int code, String description, Set<DlbSwtMtMessageTemplateType> dlbSwtMtMessageTemplateTypes) {
       this.code = code;
       this.description = description;
       this.dlbSwtMtMessageTemplateTypes = dlbSwtMtMessageTemplateTypes;
    }
   
     @Id 

    
    @Column(name="CODE", unique=true, nullable=false)
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }

    
    @Column(name="DESCRIPTION", length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbSwtMtMessageTemplateCategory")
    public Set<DlbSwtMtMessageTemplateType> getDlbSwtMtMessageTemplateTypes() {
        return this.dlbSwtMtMessageTemplateTypes;
    }
    
    public void setDlbSwtMtMessageTemplateTypes(Set<DlbSwtMtMessageTemplateType> dlbSwtMtMessageTemplateTypes) {
        this.dlbSwtMtMessageTemplateTypes = dlbSwtMtMessageTemplateTypes;
    }




}


