package com.epic.dlb.model;
// Generated Mar 27, 2020 3:49:15 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DlbWbGamePrizeType generated by hbm2java
 */
@Entity
@Table(name="DLB_WB_GAME_PRIZE_TYPE"
   
)
public class DlbWbGamePrizeType  implements java.io.Serializable {


     private Integer id;
     private String prizeType;
     private Set<DlbWbGamePrize> dlbWbGamePrizes = new HashSet<DlbWbGamePrize>(0);

    public DlbWbGamePrizeType() {
    }

    public DlbWbGamePrizeType(String prizeType, Set<DlbWbGamePrize> dlbWbGamePrizes) {
       this.prizeType = prizeType;
       this.dlbWbGamePrizes = dlbWbGamePrizes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="PRIZE_TYPE", length=100)
    public String getPrizeType() {
        return this.prizeType;
    }
    
    public void setPrizeType(String prizeType) {
        this.prizeType = prizeType;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbWbGamePrizeType")
    public Set<DlbWbGamePrize> getDlbWbGamePrizes() {
        return this.dlbWbGamePrizes;
    }
    
    public void setDlbWbGamePrizes(Set<DlbWbGamePrize> dlbWbGamePrizes) {
        this.dlbWbGamePrizes = dlbWbGamePrizes;
    }




}


