package com.epic.dlb.model;
// Generated Jun 15, 2018 2:03:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DlbWbUserPriviledge generated by hbm2java
 */
@Entity
@Table(name="DLB_WB_USER_PRIVILEDGE"
    
)
public class DlbWbUserPriviledge  implements java.io.Serializable {


     private DlbWbUserPriviledgeId id;
     private DlbWbPage dlbWbPage;
     private DlbWbSection dlbWbSection;
     private DlbWbSubSection dlbWbSubSection;
     private DlbWbUserRole dlbWbUserRole;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private Date createdtime;

    public DlbWbUserPriviledge() {
    }

	
    public DlbWbUserPriviledge(DlbWbUserPriviledgeId id, DlbWbPage dlbWbPage, DlbWbSection dlbWbSection, DlbWbSubSection dlbWbSubSection, DlbWbUserRole dlbWbUserRole) {
        this.id = id;
        this.dlbWbPage = dlbWbPage;
        this.dlbWbSection = dlbWbSection;
        this.dlbWbSubSection = dlbWbSubSection;
        this.dlbWbUserRole = dlbWbUserRole;
    }
    public DlbWbUserPriviledge(DlbWbUserPriviledgeId id, DlbWbPage dlbWbPage, DlbWbSection dlbWbSection, DlbWbSubSection dlbWbSubSection, DlbWbUserRole dlbWbUserRole, String lastupdateduser, Date lastupdatedtime, Date createdtime) {
       this.id = id;
       this.dlbWbPage = dlbWbPage;
       this.dlbWbSection = dlbWbSection;
       this.dlbWbSubSection = dlbWbSubSection;
       this.dlbWbUserRole = dlbWbUserRole;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.createdtime = createdtime;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="userrole", column=@Column(name="USERROLE", nullable=false, length=16) ), 
        @AttributeOverride(name="section", column=@Column(name="SECTION", nullable=false, length=16) ), 
        @AttributeOverride(name="page", column=@Column(name="PAGE", nullable=false, length=16) ), 
        @AttributeOverride(name="subsection", column=@Column(name="SUBSECTION", nullable=false, length=16) ) } )
    public DlbWbUserPriviledgeId getId() {
        return this.id;
    }
    
    public void setId(DlbWbUserPriviledgeId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PAGE", nullable=false, insertable=false, updatable=false)
    public DlbWbPage getDlbWbPage() {
        return this.dlbWbPage;
    }
    
    public void setDlbWbPage(DlbWbPage dlbWbPage) {
        this.dlbWbPage = dlbWbPage;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECTION", nullable=false, insertable=false, updatable=false)
    public DlbWbSection getDlbWbSection() {
        return this.dlbWbSection;
    }
    
    public void setDlbWbSection(DlbWbSection dlbWbSection) {
        this.dlbWbSection = dlbWbSection;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SUBSECTION", nullable=false, insertable=false, updatable=false)
    public DlbWbSubSection getDlbWbSubSection() {
        return this.dlbWbSubSection;
    }
    
    public void setDlbWbSubSection(DlbWbSubSection dlbWbSubSection) {
        this.dlbWbSubSection = dlbWbSubSection;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USERROLE", nullable=false, insertable=false, updatable=false)
    public DlbWbUserRole getDlbWbUserRole() {
        return this.dlbWbUserRole;
    }
    
    public void setDlbWbUserRole(DlbWbUserRole dlbWbUserRole) {
        this.dlbWbUserRole = dlbWbUserRole;
    }

    
    @Column(name="LASTUPDATEDUSER", length=128)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }




}


