package com.epic.dlb.model;
// Generated Jun 15, 2018 2:03:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DlbWbResultDetails generated by hbm2java
 */
@Entity
@Table(name="DLB_WB_RESULT_DETAILS"
    
)
public class DlbWbResultDetails  implements java.io.Serializable {


     private Integer id;
     private DlbWbProduct dlbWbProduct;
     private DlbWbProductItem dlbWbProductItem;
     private DlbWbResult dlbWbResult;
     private DlbWbWeekDay dlbWbWeekDay;
     private int drawNo;
     private Date date;
     private String value;
     private String lastUpdatedUser;
     private Date lastUpdatedTime;
     private Date createdTime;

    public DlbWbResultDetails() {
    }

	
    public DlbWbResultDetails(DlbWbProduct dlbWbProduct, DlbWbProductItem dlbWbProductItem, DlbWbResult dlbWbResult, DlbWbWeekDay dlbWbWeekDay, int drawNo, String value) {
        this.dlbWbProduct = dlbWbProduct;
        this.dlbWbProductItem = dlbWbProductItem;
        this.dlbWbResult = dlbWbResult;
        this.dlbWbWeekDay = dlbWbWeekDay;
        this.drawNo = drawNo;
        this.value = value;
    }
    public DlbWbResultDetails(DlbWbProduct dlbWbProduct, DlbWbProductItem dlbWbProductItem, DlbWbResult dlbWbResult, DlbWbWeekDay dlbWbWeekDay, int drawNo, Date date, String value, String lastUpdatedUser, Date lastUpdatedTime, Date createdTime) {
       this.dlbWbProduct = dlbWbProduct;
       this.dlbWbProductItem = dlbWbProductItem;
       this.dlbWbResult = dlbWbResult;
       this.dlbWbWeekDay = dlbWbWeekDay;
       this.drawNo = drawNo;
       this.date = date;
       this.value = value;
       this.lastUpdatedUser = lastUpdatedUser;
       this.lastUpdatedTime = lastUpdatedTime;
       this.createdTime = createdTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PRODUCT", nullable=false)
    public DlbWbProduct getDlbWbProduct() {
        return this.dlbWbProduct;
    }
    
    public void setDlbWbProduct(DlbWbProduct dlbWbProduct) {
        this.dlbWbProduct = dlbWbProduct;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PRODUCT_ITEM", nullable=false)
    public DlbWbProductItem getDlbWbProductItem() {
        return this.dlbWbProductItem;
    }
    
    public void setDlbWbProductItem(DlbWbProductItem dlbWbProductItem) {
        this.dlbWbProductItem = dlbWbProductItem;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RESULT_ID", nullable=false)
    public DlbWbResult getDlbWbResult() {
        return this.dlbWbResult;
    }
    
    public void setDlbWbResult(DlbWbResult dlbWbResult) {
        this.dlbWbResult = dlbWbResult;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DAY", nullable=false)
    public DlbWbWeekDay getDlbWbWeekDay() {
        return this.dlbWbWeekDay;
    }
    
    public void setDlbWbWeekDay(DlbWbWeekDay dlbWbWeekDay) {
        this.dlbWbWeekDay = dlbWbWeekDay;
    }

    
    @Column(name="DRAW_NO", nullable=false)
    public int getDrawNo() {
        return this.drawNo;
    }
    
    public void setDrawNo(int drawNo) {
        this.drawNo = drawNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE", length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="VALUE", nullable=false, length=100)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    
    @Column(name="LAST_UPDATED_USER", length=128)
    public String getLastUpdatedUser() {
        return this.lastUpdatedUser;
    }
    
    public void setLastUpdatedUser(String lastUpdatedUser) {
        this.lastUpdatedUser = lastUpdatedUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED_TIME", length=19)
    public Date getLastUpdatedTime() {
        return this.lastUpdatedTime;
    }
    
    public void setLastUpdatedTime(Date lastUpdatedTime) {
        this.lastUpdatedTime = lastUpdatedTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_TIME", length=19)
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }




}


