package com.epic.dlb.model;
// Generated Jun 7, 2020 10:19:08 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DlbWbGameResult generated by hbm2java
 */
@Entity
@Table(name="DLB_WB_GAME_RESULT"
)
public class DlbWbGameResult  implements java.io.Serializable {


     private Integer id;
     private DlbWbGame dlbWbGame;
     private DlbWbResult dlbWbResult;
     private String winSpNumber;

    public DlbWbGameResult() {
    }

    public DlbWbGameResult(DlbWbGame dlbWbGame, DlbWbResult dlbWbResult, String winSpNumber) {
       this.dlbWbGame = dlbWbGame;
       this.dlbWbResult = dlbWbResult;
       this.winSpNumber = winSpNumber;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GAME_ID", nullable=false)
    public DlbWbGame getDlbWbGame() {
        return this.dlbWbGame;
    }
    
    public void setDlbWbGame(DlbWbGame dlbWbGame) {
        this.dlbWbGame = dlbWbGame;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RESULT_ID", nullable=false)
    public DlbWbResult getDlbWbResult() {
        return this.dlbWbResult;
    }
    
    public void setDlbWbResult(DlbWbResult dlbWbResult) {
        this.dlbWbResult = dlbWbResult;
    }

    
    @Column(name="WIN_SP_NUMBER", nullable=false, length=45)
    public String getWinSpNumber() {
        return this.winSpNumber;
    }
    
    public void setWinSpNumber(String winSpNumber) {
        this.winSpNumber = winSpNumber;
    }




}


