package com.epic.dlb.model;
// Generated Jun 15, 2018 2:03:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DlbWbTicketFileErrorDetails generated by hbm2java
 */
@Entity
@Table(name="DLB_WB_TICKET_FILE_ERROR_DETAILS"
    
)
public class DlbWbTicketFileErrorDetails  implements java.io.Serializable {


     private Integer id;
     private DlbWbTicketFile dlbWbTicketFile;
     private String data;
     private String reason;
     private String lastUpdatedUser;
     private Date lastUpdatedTime;
     private Date createdTime;

    public DlbWbTicketFileErrorDetails() {
    }

	
    public DlbWbTicketFileErrorDetails(DlbWbTicketFile dlbWbTicketFile, String data, String reason) {
        this.dlbWbTicketFile = dlbWbTicketFile;
        this.data = data;
        this.reason = reason;
    }
    public DlbWbTicketFileErrorDetails(DlbWbTicketFile dlbWbTicketFile, String data, String reason, String lastUpdatedUser, Date lastUpdatedTime, Date createdTime) {
       this.dlbWbTicketFile = dlbWbTicketFile;
       this.data = data;
       this.reason = reason;
       this.lastUpdatedUser = lastUpdatedUser;
       this.lastUpdatedTime = lastUpdatedTime;
       this.createdTime = createdTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TICKET_ID", nullable=false)
    public DlbWbTicketFile getDlbWbTicketFile() {
        return this.dlbWbTicketFile;
    }
    
    public void setDlbWbTicketFile(DlbWbTicketFile dlbWbTicketFile) {
        this.dlbWbTicketFile = dlbWbTicketFile;
    }

    
    @Column(name="DATA", nullable=false, length=256)
    public String getData() {
        return this.data;
    }
    
    public void setData(String data) {
        this.data = data;
    }

    
    @Column(name="REASON", nullable=false, length=512)
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }

    
    @Column(name="LAST_UPDATED_USER", length=128)
    public String getLastUpdatedUser() {
        return this.lastUpdatedUser;
    }
    
    public void setLastUpdatedUser(String lastUpdatedUser) {
        this.lastUpdatedUser = lastUpdatedUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED_TIME", length=19)
    public Date getLastUpdatedTime() {
        return this.lastUpdatedTime;
    }
    
    public void setLastUpdatedTime(Date lastUpdatedTime) {
        this.lastUpdatedTime = lastUpdatedTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_TIME", length=19)
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }




}


