package com.epic.dlb.model;
// Generated Jun 15, 2018 2:03:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DlbWbUserRole generated by hbm2java
 */
@Entity
@Table(name="DLB_WB_USER_ROLE"
    
)
public class DlbWbUserRole  implements java.io.Serializable {


     private String userrolecode;
     private DlbStatus dlbStatus;
     private DlbWbUserRoleCategory dlbWbUserRoleCategory;
     private String description;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private Date createdtime;
     private Set<DlbWbUserPriviledge> dlbWbUserPriviledges = new HashSet<DlbWbUserPriviledge>(0);
     private Set<DlbWbSectionPriviledge> dlbWbSectionPriviledges = new HashSet<DlbWbSectionPriviledge>(0);
     private Set<DlbWbSystemUser> dlbWbSystemUsers = new HashSet<DlbWbSystemUser>(0);

    public DlbWbUserRole() {
    }

	
    public DlbWbUserRole(String userrolecode) {
        this.userrolecode = userrolecode;
    }
    public DlbWbUserRole(String userrolecode, DlbStatus dlbStatus, DlbWbUserRoleCategory dlbWbUserRoleCategory, String description, String lastupdateduser, Date lastupdatedtime, Date createdtime, Set<DlbWbUserPriviledge> dlbWbUserPriviledges, Set<DlbWbSectionPriviledge> dlbWbSectionPriviledges, Set<DlbWbSystemUser> dlbWbSystemUsers) {
       this.userrolecode = userrolecode;
       this.dlbStatus = dlbStatus;
       this.dlbWbUserRoleCategory = dlbWbUserRoleCategory;
       this.description = description;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.createdtime = createdtime;
       this.dlbWbUserPriviledges = dlbWbUserPriviledges;
       this.dlbWbSectionPriviledges = dlbWbSectionPriviledges;
       this.dlbWbSystemUsers = dlbWbSystemUsers;
    }
   
     @Id 

    
    @Column(name="USERROLECODE", unique=true, nullable=false, length=16)
    public String getUserrolecode() {
        return this.userrolecode;
    }
    
    public void setUserrolecode(String userrolecode) {
        this.userrolecode = userrolecode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS")
    public DlbStatus getDlbStatus() {
        return this.dlbStatus;
    }
    
    public void setDlbStatus(DlbStatus dlbStatus) {
        this.dlbStatus = dlbStatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USERROLECATEGORY")
    public DlbWbUserRoleCategory getDlbWbUserRoleCategory() {
        return this.dlbWbUserRoleCategory;
    }
    
    public void setDlbWbUserRoleCategory(DlbWbUserRoleCategory dlbWbUserRoleCategory) {
        this.dlbWbUserRoleCategory = dlbWbUserRoleCategory;
    }

    
    @Column(name="DESCRIPTION", length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="LASTUPDATEDUSER", length=128)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbWbUserRole")
    public Set<DlbWbUserPriviledge> getDlbWbUserPriviledges() {
        return this.dlbWbUserPriviledges;
    }
    
    public void setDlbWbUserPriviledges(Set<DlbWbUserPriviledge> dlbWbUserPriviledges) {
        this.dlbWbUserPriviledges = dlbWbUserPriviledges;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbWbUserRole")
    public Set<DlbWbSectionPriviledge> getDlbWbSectionPriviledges() {
        return this.dlbWbSectionPriviledges;
    }
    
    public void setDlbWbSectionPriviledges(Set<DlbWbSectionPriviledge> dlbWbSectionPriviledges) {
        this.dlbWbSectionPriviledges = dlbWbSectionPriviledges;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbWbUserRole")
    public Set<DlbWbSystemUser> getDlbWbSystemUsers() {
        return this.dlbWbSystemUsers;
    }
    
    public void setDlbWbSystemUsers(Set<DlbWbSystemUser> dlbWbSystemUsers) {
        this.dlbWbSystemUsers = dlbWbSystemUsers;
    }




}


