package com.epic.dlb.model;
// Generated Apr 21, 2020 1:36:58 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DlbWbResultSpDetails generated by hbm2java
 */
@Entity
@Table(name="DLB_WB_RESULT_SP_DETAILS"
)
public class DlbWbResultSpDetails  implements java.io.Serializable {


     private Integer id;
     private DlbWbGame dlbWbGame;
     private DlbWbResult dlbWbResult;
     private String value;

    public DlbWbResultSpDetails() {
    }

    public DlbWbResultSpDetails(DlbWbGame dlbWbGame, DlbWbResult dlbWbResult, String value) {
       this.dlbWbGame = dlbWbGame;
       this.dlbWbResult = dlbWbResult;
       this.value = value;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GAME_ID")
    public DlbWbGame getDlbWbGame() {
        return this.dlbWbGame;
    }
    
    public void setDlbWbGame(DlbWbGame dlbWbGame) {
        this.dlbWbGame = dlbWbGame;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RESULT_ID")
    public DlbWbResult getDlbWbResult() {
        return this.dlbWbResult;
    }
    
    public void setDlbWbResult(DlbWbResult dlbWbResult) {
        this.dlbWbResult = dlbWbResult;
    }

    
    @Column(name="VALUE", length=50)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


