package com.epic.dlb.model;
// Generated Jun 15, 2018 2:03:02 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * DlbWbTicketFile generated by hbm2java
 */
@Entity
@Table(name = "DLB_WB_TICKET_FILE"
)
public class DlbWbTicketFile implements java.io.Serializable {

    private Integer id;
    private DlbStatus dlbStatus;
    private DlbWbEmployee dlbWbEmployeeByUploadBy;
    private DlbWbEmployee dlbWbEmployeeByApprovedBy;
    private DlbWbProduct dlbWbProduct;
    private DlbWbProductProfile dlbWbProductProfile;
    private String drawNo;
    private Date date;
    private String hash;
    private String originHash;
    private String macAddress;
    private String productDescription;
    private Boolean filenameCheck;
    private Boolean macCheck;
    private Boolean hashCheck;
    private String filePath;
    private Integer noOfTicket;
    private String lastUpdatedUser;
    private Date lastUpdatedTime;
    private Date createdTime;
    private Boolean tokenCheck;
    private String jackpot;
    private DlbStatus dlbStatusByIsSpecial;
    private DlbWbGameProfile dlbWbGameProfile;
    private Set<DlbWbTicket> dlbWbTickets = new HashSet<DlbWbTicket>(0);
    private Set<DlbWbTicketFileErrorDetails> dlbWbTicketFileErrorDetailses = new HashSet<DlbWbTicketFileErrorDetails>(0);

    public DlbWbTicketFile() {
    }

    public DlbWbTicketFile(DlbWbEmployee dlbWbEmployeeByUploadBy, DlbWbProduct dlbWbProduct, String drawNo) {
        this.dlbWbEmployeeByUploadBy = dlbWbEmployeeByUploadBy;
        this.dlbWbProduct = dlbWbProduct;
        this.drawNo = drawNo;
    }

    public DlbWbTicketFile(DlbStatus dlbStatus, DlbWbEmployee dlbWbEmployeeByUploadBy, DlbWbEmployee dlbWbEmployeeByApprovedBy, DlbWbProduct dlbWbProduct, DlbWbProductProfile dlbWbProductProfile, String drawNo, Date date, String hash, String macAddress, String productDescription, Boolean filenameCheck, Boolean macCheck, Boolean hashCheck, String filePath, Integer noOfTicket, String lastUpdatedUser, Date lastUpdatedTime, Date createdTime, Boolean tokenCheck, String jackpot, Set<DlbWbTicket> dlbWbTickets, Set<DlbWbTicketFileErrorDetails> dlbWbTicketFileErrorDetailses) {
        this.dlbStatus = dlbStatus;
        this.dlbWbEmployeeByUploadBy = dlbWbEmployeeByUploadBy;
        this.dlbWbEmployeeByApprovedBy = dlbWbEmployeeByApprovedBy;
        this.dlbWbProduct = dlbWbProduct;
        this.dlbWbProductProfile = dlbWbProductProfile;
        this.drawNo = drawNo;
        this.date = date;
        this.hash = hash;
        this.macAddress = macAddress;
        this.productDescription = productDescription;
        this.filenameCheck = filenameCheck;
        this.macCheck = macCheck;
        this.hashCheck = hashCheck;
        this.filePath = filePath;
        this.noOfTicket = noOfTicket;
        this.lastUpdatedUser = lastUpdatedUser;
        this.lastUpdatedTime = lastUpdatedTime;
        this.createdTime = createdTime;
        this.tokenCheck = tokenCheck;
        this.jackpot = jackpot;
        this.dlbWbTickets = dlbWbTickets;
        this.dlbWbTicketFileErrorDetailses = dlbWbTicketFileErrorDetailses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PENDING_APPROVAL")
    public DlbStatus getDlbStatus() {
        return this.dlbStatus;
    }

    public void setDlbStatus(DlbStatus dlbStatus) {
        this.dlbStatus = dlbStatus;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "UPLOAD_BY", nullable = false)
    public DlbWbEmployee getDlbWbEmployeeByUploadBy() {
        return this.dlbWbEmployeeByUploadBy;
    }

    public void setDlbWbEmployeeByUploadBy(DlbWbEmployee dlbWbEmployeeByUploadBy) {
        this.dlbWbEmployeeByUploadBy = dlbWbEmployeeByUploadBy;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "APPROVED_BY")
    public DlbWbEmployee getDlbWbEmployeeByApprovedBy() {
        return this.dlbWbEmployeeByApprovedBy;
    }

    public void setDlbWbEmployeeByApprovedBy(DlbWbEmployee dlbWbEmployeeByApprovedBy) {
        this.dlbWbEmployeeByApprovedBy = dlbWbEmployeeByApprovedBy;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PRODUCT_CODE", nullable = false)
    public DlbWbProduct getDlbWbProduct() {
        return this.dlbWbProduct;
    }

    public void setDlbWbProduct(DlbWbProduct dlbWbProduct) {
        this.dlbWbProduct = dlbWbProduct;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PROFILE_ID")
    public DlbWbProductProfile getDlbWbProductProfile() {
        return this.dlbWbProductProfile;
    }

    public void setDlbWbProductProfile(DlbWbProductProfile dlbWbProductProfile) {
        this.dlbWbProductProfile = dlbWbProductProfile;
    }

    @Column(name = "DRAW_NO", nullable = false, length = 16)
    public String getDrawNo() {
        return this.drawNo;
    }

    public void setDrawNo(String drawNo) {
        this.drawNo = drawNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DATE", length = 10)
    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    @Column(name = "HASH", length = 512)
    public String getHash() {
        return this.hash;
    }

    public void setHash(String hash) {
        this.hash = hash;
    }

    @Column(name = "MAC_ADDRESS", length = 64)
    public String getMacAddress() {
        return this.macAddress;
    }

    public void setMacAddress(String macAddress) {
        this.macAddress = macAddress;
    }

    @Column(name = "PRODUCT_DESCRIPTION", length = 128)
    public String getProductDescription() {
        return this.productDescription;
    }

    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription;
    }

    @Column(name = "FILENAME_CHECK")
    public Boolean getFilenameCheck() {
        return this.filenameCheck;
    }

    public void setFilenameCheck(Boolean filenameCheck) {
        this.filenameCheck = filenameCheck;
    }

    @Column(name = "MAC_CHECK")
    public Boolean getMacCheck() {
        return this.macCheck;
    }

    public void setMacCheck(Boolean macCheck) {
        this.macCheck = macCheck;
    }

    @Column(name = "HASH_CHECK")
    public Boolean getHashCheck() {
        return this.hashCheck;
    }

    public void setHashCheck(Boolean hashCheck) {
        this.hashCheck = hashCheck;
    }

    @Column(name = "FILE_PATH", length = 256)
    public String getFilePath() {
        return this.filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    @Column(name = "NO_OF_TICKET")
    public Integer getNoOfTicket() {
        return this.noOfTicket;
    }

    public void setNoOfTicket(Integer noOfTicket) {
        this.noOfTicket = noOfTicket;
    }

    @Column(name = "LAST_UPDATED_USER", length = 128)
    public String getLastUpdatedUser() {
        return this.lastUpdatedUser;
    }

    public void setLastUpdatedUser(String lastUpdatedUser) {
        this.lastUpdatedUser = lastUpdatedUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LAST_UPDATED_TIME", length = 19)
    public Date getLastUpdatedTime() {
        return this.lastUpdatedTime;
    }

    public void setLastUpdatedTime(Date lastUpdatedTime) {
        this.lastUpdatedTime = lastUpdatedTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATED_TIME", length = 19)
    public Date getCreatedTime() {
        return this.createdTime;
    }

    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    @Column(name = "TOKEN_CHECK")
    public Boolean getTokenCheck() {
        return this.tokenCheck;
    }

    public void setTokenCheck(Boolean tokenCheck) {
        this.tokenCheck = tokenCheck;
    }

    @Column(name = "JACKPOT")
    public String getJackpot() {
        return this.jackpot;
    }

    public void setJackpot(String jackpot) {
        this.jackpot = jackpot;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "dlbWbTicketFile")
    public Set<DlbWbTicket> getDlbWbTickets() {
        return this.dlbWbTickets;
    }

    public void setDlbWbTickets(Set<DlbWbTicket> dlbWbTickets) {
        this.dlbWbTickets = dlbWbTickets;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "dlbWbTicketFile")
    public Set<DlbWbTicketFileErrorDetails> getDlbWbTicketFileErrorDetailses() {
        return this.dlbWbTicketFileErrorDetailses;
    }

    public void setDlbWbTicketFileErrorDetailses(Set<DlbWbTicketFileErrorDetails> dlbWbTicketFileErrorDetailses) {
        this.dlbWbTicketFileErrorDetailses = dlbWbTicketFileErrorDetailses;
    }

    @Transient
    public String getOriginHash() {
        return originHash;
    }

    public void setOriginHash(String originHash) {
        this.originHash = originHash;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "IS_SPECIAL", nullable = false)
    public DlbStatus getDlbStatusByIsSpecial() {
        return this.dlbStatusByIsSpecial;
    }

    public void setDlbStatusByIsSpecial(DlbStatus dlbStatusByIsSpecial) {
        this.dlbStatusByIsSpecial = dlbStatusByIsSpecial;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SP_GAME_PROFILE")
    public DlbWbGameProfile getDlbWbGameProfile() {
        return this.dlbWbGameProfile;
    }

    public void setDlbWbGameProfile(DlbWbGameProfile dlbWbGameProfile) {
        this.dlbWbGameProfile = dlbWbGameProfile;
    }

}
