package com.epic.dlb.model;
// Generated Jun 15, 2018 2:03:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DlbWbPromotion generated by hbm2java
 */
@Entity
@Table(name="DLB_WB_PROMOTION"
    
)
public class DlbWbPromotion  implements java.io.Serializable {


     private Integer id;
     private DlbStatus dlbStatus;
     private String description;
     private Date validFrom;
     private Date validTo;
     private String smallImgUrl;
     private String largeImgUrl;
     private Date createdDate;

    public DlbWbPromotion() {
    }

	
    public DlbWbPromotion(String description) {
        this.description = description;
    }
    public DlbWbPromotion(DlbStatus dlbStatus, String description, Date validFrom, Date validTo, String smallImgUrl, String largeImgUrl, Date createdDate) {
       this.dlbStatus = dlbStatus;
       this.description = description;
       this.validFrom = validFrom;
       this.validTo = validTo;
       this.smallImgUrl = smallImgUrl;
       this.largeImgUrl = largeImgUrl;
       this.createdDate = createdDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STAUS")
    public DlbStatus getDlbStatus() {
        return this.dlbStatus;
    }
    
    public void setDlbStatus(DlbStatus dlbStatus) {
        this.dlbStatus = dlbStatus;
    }

    
    @Column(name="DESCRIPTION", nullable=false, length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="VALID_FROM", length=10)
    public Date getValidFrom() {
        return this.validFrom;
    }
    
    public void setValidFrom(Date validFrom) {
        this.validFrom = validFrom;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="VALID_TO", length=10)
    public Date getValidTo() {
        return this.validTo;
    }
    
    public void setValidTo(Date validTo) {
        this.validTo = validTo;
    }

    
    @Column(name="SMALL_IMG_URL", length=65535)
    public String getSmallImgUrl() {
        return this.smallImgUrl;
    }
    
    public void setSmallImgUrl(String smallImgUrl) {
        this.smallImgUrl = smallImgUrl;
    }

    
    @Column(name="LARGE_IMG_URL", length=65535)
    public String getLargeImgUrl() {
        return this.largeImgUrl;
    }
    
    public void setLargeImgUrl(String largeImgUrl) {
        this.largeImgUrl = largeImgUrl;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }




}


