package com.epic.dlb.model;
// Generated Jun 15, 2018 2:03:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DlbWbWiningFileHistory generated by hbm2java
 */
@Entity
@Table(name="DLB_WB_WINING_FILE_HISTORY"
    
)
public class DlbWbWiningFileHistory  implements java.io.Serializable {


     private Integer id;
     private DlbStatus dlbStatus;
     private DlbWbEmployee dlbWbEmployeeByUploadBy;
     private DlbWbEmployee dlbWbEmployeeByApprovedBy;
     private DlbWbProduct dlbWbProduct;
     private DlbWbWorkflow dlbWbWorkflow;
     private String drawNo;
     private Date date;
     private String hash;
     private String macAddress;
     private String productDescription;
     private String filePath;
     private String reason;
     private String lastUpdatedUser;
     private Date lastUpdatedTime;
     private Date createdTime;

    public DlbWbWiningFileHistory() {
    }

	
    public DlbWbWiningFileHistory(DlbWbEmployee dlbWbEmployeeByUploadBy, DlbWbProduct dlbWbProduct, DlbWbWorkflow dlbWbWorkflow, String drawNo) {
        this.dlbWbEmployeeByUploadBy = dlbWbEmployeeByUploadBy;
        this.dlbWbProduct = dlbWbProduct;
        this.dlbWbWorkflow = dlbWbWorkflow;
        this.drawNo = drawNo;
    }
    public DlbWbWiningFileHistory(DlbStatus dlbStatus, DlbWbEmployee dlbWbEmployeeByUploadBy, DlbWbEmployee dlbWbEmployeeByApprovedBy, DlbWbProduct dlbWbProduct, DlbWbWorkflow dlbWbWorkflow, String drawNo, Date date, String hash, String macAddress, String productDescription, String filePath, String reason, String lastUpdatedUser, Date lastUpdatedTime, Date createdTime) {
       this.dlbStatus = dlbStatus;
       this.dlbWbEmployeeByUploadBy = dlbWbEmployeeByUploadBy;
       this.dlbWbEmployeeByApprovedBy = dlbWbEmployeeByApprovedBy;
       this.dlbWbProduct = dlbWbProduct;
       this.dlbWbWorkflow = dlbWbWorkflow;
       this.drawNo = drawNo;
       this.date = date;
       this.hash = hash;
       this.macAddress = macAddress;
       this.productDescription = productDescription;
       this.filePath = filePath;
       this.reason = reason;
       this.lastUpdatedUser = lastUpdatedUser;
       this.lastUpdatedTime = lastUpdatedTime;
       this.createdTime = createdTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS")
    public DlbStatus getDlbStatus() {
        return this.dlbStatus;
    }
    
    public void setDlbStatus(DlbStatus dlbStatus) {
        this.dlbStatus = dlbStatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="UPLOAD_BY", nullable=false)
    public DlbWbEmployee getDlbWbEmployeeByUploadBy() {
        return this.dlbWbEmployeeByUploadBy;
    }
    
    public void setDlbWbEmployeeByUploadBy(DlbWbEmployee dlbWbEmployeeByUploadBy) {
        this.dlbWbEmployeeByUploadBy = dlbWbEmployeeByUploadBy;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="APPROVED_BY")
    public DlbWbEmployee getDlbWbEmployeeByApprovedBy() {
        return this.dlbWbEmployeeByApprovedBy;
    }
    
    public void setDlbWbEmployeeByApprovedBy(DlbWbEmployee dlbWbEmployeeByApprovedBy) {
        this.dlbWbEmployeeByApprovedBy = dlbWbEmployeeByApprovedBy;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PRODUCT_CODE", nullable=false)
    public DlbWbProduct getDlbWbProduct() {
        return this.dlbWbProduct;
    }
    
    public void setDlbWbProduct(DlbWbProduct dlbWbProduct) {
        this.dlbWbProduct = dlbWbProduct;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CURRENT_STAGE", nullable=false)
    public DlbWbWorkflow getDlbWbWorkflow() {
        return this.dlbWbWorkflow;
    }
    
    public void setDlbWbWorkflow(DlbWbWorkflow dlbWbWorkflow) {
        this.dlbWbWorkflow = dlbWbWorkflow;
    }

    
    @Column(name="DRAW_NO", nullable=false, length=16)
    public String getDrawNo() {
        return this.drawNo;
    }
    
    public void setDrawNo(String drawNo) {
        this.drawNo = drawNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE", length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="HASH", length=512)
    public String getHash() {
        return this.hash;
    }
    
    public void setHash(String hash) {
        this.hash = hash;
    }

    
    @Column(name="MAC_ADDRESS", length=64)
    public String getMacAddress() {
        return this.macAddress;
    }
    
    public void setMacAddress(String macAddress) {
        this.macAddress = macAddress;
    }

    
    @Column(name="PRODUCT_DESCRIPTION", length=128)
    public String getProductDescription() {
        return this.productDescription;
    }
    
    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription;
    }

    
    @Column(name="FILE_PATH", length=256)
    public String getFilePath() {
        return this.filePath;
    }
    
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    
    @Column(name="REASON", length=1024)
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }

    
    @Column(name="LAST_UPDATED_USER", length=128)
    public String getLastUpdatedUser() {
        return this.lastUpdatedUser;
    }
    
    public void setLastUpdatedUser(String lastUpdatedUser) {
        this.lastUpdatedUser = lastUpdatedUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED_TIME", length=19)
    public Date getLastUpdatedTime() {
        return this.lastUpdatedTime;
    }
    
    public void setLastUpdatedTime(Date lastUpdatedTime) {
        this.lastUpdatedTime = lastUpdatedTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_TIME", length=19)
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }




}


