package com.epic.dlb.model;
// Generated Jun 15, 2018 2:03:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DlbWbWeekDay generated by hbm2java
 */
@Entity
@Table(name="DLB_WB_WEEK_DAY"
    
)
public class DlbWbWeekDay  implements java.io.Serializable {


     private String dayCode;
     private DlbStatus dlbStatus;
     private String description;
     private String lastUpdatedUser;
     private Date lastUpdatedTime;
     private Date createdTime;
     private Set<DlbWbProductList> dlbWbProductLists = new HashSet<DlbWbProductList>(0);
     private Set<DlbWbProductProfile> dlbWbProductProfiles = new HashSet<DlbWbProductProfile>(0);
     private Set<DlbWbProductProfileDetails> dlbWbProductProfileDetailses = new HashSet<DlbWbProductProfileDetails>(0);
     private Set<DlbWbResultDetails> dlbWbResultDetailses = new HashSet<DlbWbResultDetails>(0);
     private Set<DlbWbResult> dlbWbResults = new HashSet<DlbWbResult>(0);

    public DlbWbWeekDay() {
    }

	
    public DlbWbWeekDay(String dayCode, DlbStatus dlbStatus, String description) {
        this.dayCode = dayCode;
        this.dlbStatus = dlbStatus;
        this.description = description;
    }
    public DlbWbWeekDay(String dayCode, DlbStatus dlbStatus, String description, String lastUpdatedUser, Date lastUpdatedTime, Date createdTime, Set<DlbWbProductList> dlbWbProductLists, Set<DlbWbProductProfile> dlbWbProductProfiles, Set<DlbWbProductProfileDetails> dlbWbProductProfileDetailses, Set<DlbWbResultDetails> dlbWbResultDetailses, Set<DlbWbResult> dlbWbResults) {
       this.dayCode = dayCode;
       this.dlbStatus = dlbStatus;
       this.description = description;
       this.lastUpdatedUser = lastUpdatedUser;
       this.lastUpdatedTime = lastUpdatedTime;
       this.createdTime = createdTime;
       this.dlbWbProductLists = dlbWbProductLists;
       this.dlbWbProductProfiles = dlbWbProductProfiles;
       this.dlbWbProductProfileDetailses = dlbWbProductProfileDetailses;
       this.dlbWbResultDetailses = dlbWbResultDetailses;
       this.dlbWbResults = dlbWbResults;
    }
   
     @Id 

    
    @Column(name="DAY_CODE", unique=true, nullable=false, length=16)
    public String getDayCode() {
        return this.dayCode;
    }
    
    public void setDayCode(String dayCode) {
        this.dayCode = dayCode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS", nullable=false)
    public DlbStatus getDlbStatus() {
        return this.dlbStatus;
    }
    
    public void setDlbStatus(DlbStatus dlbStatus) {
        this.dlbStatus = dlbStatus;
    }

    
    @Column(name="DESCRIPTION", nullable=false, length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="LAST_UPDATED_USER", length=128)
    public String getLastUpdatedUser() {
        return this.lastUpdatedUser;
    }
    
    public void setLastUpdatedUser(String lastUpdatedUser) {
        this.lastUpdatedUser = lastUpdatedUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED_TIME", length=19)
    public Date getLastUpdatedTime() {
        return this.lastUpdatedTime;
    }
    
    public void setLastUpdatedTime(Date lastUpdatedTime) {
        this.lastUpdatedTime = lastUpdatedTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_TIME", length=19)
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbWbWeekDay")
    public Set<DlbWbProductList> getDlbWbProductLists() {
        return this.dlbWbProductLists;
    }
    
    public void setDlbWbProductLists(Set<DlbWbProductList> dlbWbProductLists) {
        this.dlbWbProductLists = dlbWbProductLists;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbWbWeekDay")
    public Set<DlbWbProductProfile> getDlbWbProductProfiles() {
        return this.dlbWbProductProfiles;
    }
    
    public void setDlbWbProductProfiles(Set<DlbWbProductProfile> dlbWbProductProfiles) {
        this.dlbWbProductProfiles = dlbWbProductProfiles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbWbWeekDay")
    public Set<DlbWbProductProfileDetails> getDlbWbProductProfileDetailses() {
        return this.dlbWbProductProfileDetailses;
    }
    
    public void setDlbWbProductProfileDetailses(Set<DlbWbProductProfileDetails> dlbWbProductProfileDetailses) {
        this.dlbWbProductProfileDetailses = dlbWbProductProfileDetailses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbWbWeekDay")
    public Set<DlbWbResultDetails> getDlbWbResultDetailses() {
        return this.dlbWbResultDetailses;
    }
    
    public void setDlbWbResultDetailses(Set<DlbWbResultDetails> dlbWbResultDetailses) {
        this.dlbWbResultDetailses = dlbWbResultDetailses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbWbWeekDay")
    public Set<DlbWbResult> getDlbWbResults() {
        return this.dlbWbResults;
    }
    
    public void setDlbWbResults(Set<DlbWbResult> dlbWbResults) {
        this.dlbWbResults = dlbWbResults;
    }




}


