package com.epic.dlb.model;
// Generated Oct 1, 2018 7:23:18 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DlbWbCeftTxnHistory generated by hbm2java
 */
@Entity
@Table(name = "DLB_WB_CEFT_TXN_HISTORY"
)
public class DlbWbCeftTxnHistory implements java.io.Serializable {

    private Integer id;
    private DlbWbEmployee dlbWbEmployee;
    private String fileHash;
    private Integer noOfRecords;
    private String totalAmount;
    private String lastUpdatedUser;
    private Date lastUpdatedTime;
    private Date createdTime;
    private DlbStatus dlbStatus;
    private Integer sequenceNo;

    public DlbWbCeftTxnHistory() {
    }

    public DlbWbCeftTxnHistory(DlbWbEmployee dlbWbEmployee, String fileHash, Integer noOfRecords, String totalAmount, String lastUpdatedUser, Date lastUpdatedTime, Date createdTime) {
        this.dlbWbEmployee = dlbWbEmployee;
        this.fileHash = fileHash;
        this.noOfRecords = noOfRecords;
        this.totalAmount = totalAmount;
        this.lastUpdatedUser = lastUpdatedUser;
        this.lastUpdatedTime = lastUpdatedTime;
        this.createdTime = createdTime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "EMPLOYEE")
    public DlbWbEmployee getDlbWbEmployee() {
        return this.dlbWbEmployee;
    }

    public void setDlbWbEmployee(DlbWbEmployee dlbWbEmployee) {
        this.dlbWbEmployee = dlbWbEmployee;
    }

    @Column(name = "FILE_HASH", length = 512)
    public String getFileHash() {
        return this.fileHash;
    }

    public void setFileHash(String fileHash) {
        this.fileHash = fileHash;
    }

    @Column(name = "NO_OF_RECORDS")
    public Integer getNoOfRecords() {
        return this.noOfRecords;
    }

    public void setNoOfRecords(Integer noOfRecords) {
        this.noOfRecords = noOfRecords;
    }

    @Column(name = "TOTAL_AMOUNT")
    public String getTotalAmount() {
        return this.totalAmount;
    }

    public void setTotalAmount(String totalAmount) {
        this.totalAmount = totalAmount;
    }

    @Column(name = "LAST_UPDATED_USER", length = 128)
    public String getLastUpdatedUser() {
        return this.lastUpdatedUser;
    }

    public void setLastUpdatedUser(String lastUpdatedUser) {
        this.lastUpdatedUser = lastUpdatedUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LAST_UPDATED_TIME", length = 19)
    public Date getLastUpdatedTime() {
        return this.lastUpdatedTime;
    }

    public void setLastUpdatedTime(Date lastUpdatedTime) {
        this.lastUpdatedTime = lastUpdatedTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATED_TIME", length = 19)
    public Date getCreatedTime() {
        return this.createdTime;
    }

    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "STATUS")
    public DlbStatus getDlbStatus() {
        return dlbStatus;
    }

    public void setDlbStatus(DlbStatus dlbStatus) {
        this.dlbStatus = dlbStatus;
    }

    @Column(name = "SEQUENCE_NO")
    public Integer getSequenceNo() {
        return sequenceNo;
    }

    public void setSequenceNo(Integer sequenceNo) {
        this.sequenceNo = sequenceNo;
    }

}
