package com.epic.dlb.model;
// Generated Jun 15, 2018 2:03:02 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DlbWbSymbol generated by hbm2java
 */
@Entity
@Table(name="DLB_WB_SYMBOL"
    
)
public class DlbWbSymbol  implements java.io.Serializable {


     private String code;
     private DlbWbProductItem dlbWbProductItem;
     private String description;

    public DlbWbSymbol() {
    }

	
    public DlbWbSymbol(String code) {
        this.code = code;
    }
    public DlbWbSymbol(String code, DlbWbProductItem dlbWbProductItem, String description) {
       this.code = code;
       this.dlbWbProductItem = dlbWbProductItem;
       this.description = description;
    }
   
     @Id 

    
    @Column(name="CODE", unique=true, nullable=false, length=16)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TYPE")
    public DlbWbProductItem getDlbWbProductItem() {
        return this.dlbWbProductItem;
    }
    
    public void setDlbWbProductItem(DlbWbProductItem dlbWbProductItem) {
        this.dlbWbProductItem = dlbWbProductItem;
    }

    
    @Column(name="DESCRIPTION", length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


