package com.epic.dlb.model;
// Generated Jun 15, 2018 2:03:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DlbWbProductItem generated by hbm2java
 */
@Entity
@Table(name="DLB_WB_PRODUCT_ITEM"
    
)
public class DlbWbProductItem  implements java.io.Serializable {


     private String itemCode;
     private DlbStatus dlbStatus;
     private String description;
     private String lastUpdatedUser;
     private Date lastUpdatedTime;
     private Date createdTime;
     private Set<DlbWbSymbol> dlbWbSymbols = new HashSet<DlbWbSymbol>(0);
     private Set<DlbWbResultDetails> dlbWbResultDetailses = new HashSet<DlbWbResultDetails>(0);
     private Set<DlbWbProductProfileDetails> dlbWbProductProfileDetailses = new HashSet<DlbWbProductProfileDetails>(0);

    public DlbWbProductItem() {
    }

	
    public DlbWbProductItem(String itemCode, DlbStatus dlbStatus, String description) {
        this.itemCode = itemCode;
        this.dlbStatus = dlbStatus;
        this.description = description;
    }
    public DlbWbProductItem(String itemCode, DlbStatus dlbStatus, String description, String lastUpdatedUser, Date lastUpdatedTime, Date createdTime, Set<DlbWbSymbol> dlbWbSymbols, Set<DlbWbResultDetails> dlbWbResultDetailses, Set<DlbWbProductProfileDetails> dlbWbProductProfileDetailses) {
       this.itemCode = itemCode;
       this.dlbStatus = dlbStatus;
       this.description = description;
       this.lastUpdatedUser = lastUpdatedUser;
       this.lastUpdatedTime = lastUpdatedTime;
       this.createdTime = createdTime;
       this.dlbWbSymbols = dlbWbSymbols;
       this.dlbWbResultDetailses = dlbWbResultDetailses;
       this.dlbWbProductProfileDetailses = dlbWbProductProfileDetailses;
    }
   
     @Id 

    
    @Column(name="ITEM_CODE", unique=true, nullable=false, length=16)
    public String getItemCode() {
        return this.itemCode;
    }
    
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS", nullable=false)
    public DlbStatus getDlbStatus() {
        return this.dlbStatus;
    }
    
    public void setDlbStatus(DlbStatus dlbStatus) {
        this.dlbStatus = dlbStatus;
    }

    
    @Column(name="DESCRIPTION", nullable=false, length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="LAST_UPDATED_USER", length=128)
    public String getLastUpdatedUser() {
        return this.lastUpdatedUser;
    }
    
    public void setLastUpdatedUser(String lastUpdatedUser) {
        this.lastUpdatedUser = lastUpdatedUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED_TIME", length=19)
    public Date getLastUpdatedTime() {
        return this.lastUpdatedTime;
    }
    
    public void setLastUpdatedTime(Date lastUpdatedTime) {
        this.lastUpdatedTime = lastUpdatedTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_TIME", length=19)
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbWbProductItem")
    public Set<DlbWbSymbol> getDlbWbSymbols() {
        return this.dlbWbSymbols;
    }
    
    public void setDlbWbSymbols(Set<DlbWbSymbol> dlbWbSymbols) {
        this.dlbWbSymbols = dlbWbSymbols;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbWbProductItem")
    public Set<DlbWbResultDetails> getDlbWbResultDetailses() {
        return this.dlbWbResultDetailses;
    }
    
    public void setDlbWbResultDetailses(Set<DlbWbResultDetails> dlbWbResultDetailses) {
        this.dlbWbResultDetailses = dlbWbResultDetailses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbWbProductItem")
    public Set<DlbWbProductProfileDetails> getDlbWbProductProfileDetailses() {
        return this.dlbWbProductProfileDetailses;
    }
    
    public void setDlbWbProductProfileDetailses(Set<DlbWbProductProfileDetails> dlbWbProductProfileDetailses) {
        this.dlbWbProductProfileDetailses = dlbWbProductProfileDetailses;
    }




}


