package com.epic.dlb.model;
// Generated Jun 15, 2018 2:03:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DlbWbSystemUser generated by hbm2java
 */
@Entity
@Table(name="DLB_WB_SYSTEM_USER"
    
)
public class DlbWbSystemUser  implements java.io.Serializable {


     private String username;
     private DlbStatus dlbStatus;
     private DlbWbEmployee dlbWbEmployee;
     private DlbWbUserRole dlbWbUserRole;
     private String password;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private Date createdtime;

    public DlbWbSystemUser() {
    }

	
    public DlbWbSystemUser(String username) {
        this.username = username;
    }
    public DlbWbSystemUser(String username, DlbStatus dlbStatus, DlbWbEmployee dlbWbEmployee, DlbWbUserRole dlbWbUserRole, String password, String lastupdateduser, Date lastupdatedtime, Date createdtime) {
       this.username = username;
       this.dlbStatus = dlbStatus;
       this.dlbWbEmployee = dlbWbEmployee;
       this.dlbWbUserRole = dlbWbUserRole;
       this.password = password;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.createdtime = createdtime;
    }
   
     @Id 

    
    @Column(name="USERNAME", unique=true, nullable=false, length=64)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS")
    public DlbStatus getDlbStatus() {
        return this.dlbStatus;
    }
    
    public void setDlbStatus(DlbStatus dlbStatus) {
        this.dlbStatus = dlbStatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMPLOYEE")
    public DlbWbEmployee getDlbWbEmployee() {
        return this.dlbWbEmployee;
    }
    
    public void setDlbWbEmployee(DlbWbEmployee dlbWbEmployee) {
        this.dlbWbEmployee = dlbWbEmployee;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USERROLE")
    public DlbWbUserRole getDlbWbUserRole() {
        return this.dlbWbUserRole;
    }
    
    public void setDlbWbUserRole(DlbWbUserRole dlbWbUserRole) {
        this.dlbWbUserRole = dlbWbUserRole;
    }

    
    @Column(name="PASSWORD", length=512)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="LASTUPDATEDUSER", length=128)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }




}


