package com.epic.dlb.model;
// Generated Mar 27, 2020 3:49:15 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DlbWbGameProfile generated by hbm2java
 */
@Entity
@Table(name="DLB_WB_GAME_PROFILE"
   
)   
    public class DlbWbGameProfile  implements java.io.Serializable {


     private Integer id;
     private DlbStatus dlbStatus;
     private String name;
     private Date createdDate;
     private String lastUpdatedUser;
     private Set<DlbWbGame> dlbWbGames = new HashSet<DlbWbGame>(0);
     private Set<DlbWbTicketFile> dlbWbTicketFiles = new HashSet<DlbWbTicketFile>(0);

    public DlbWbGameProfile() {
    }
    
    
     public DlbWbGameProfile( Integer id) {
         this.id = id;
    }

    public DlbWbGameProfile(DlbStatus dlbStatus, String name, Date createdDate, String lastUpdatedUser, Set<DlbWbGame> dlbWbGames, Set<DlbWbTicketFile> dlbWbTicketFiles) {
       this.dlbStatus = dlbStatus;
       this.name = name;
       this.createdDate = createdDate;
       this.lastUpdatedUser = lastUpdatedUser;
       this.dlbWbGames = dlbWbGames;
       this.dlbWbTicketFiles = dlbWbTicketFiles;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS")
    public DlbStatus getDlbStatus() {
        return this.dlbStatus;
    }
    
    public void setDlbStatus(DlbStatus dlbStatus) {
        this.dlbStatus = dlbStatus;
    }

    
    @Column(name="NAME")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="LAST_UPDATED_USER", length=128)
    public String getLastUpdatedUser() {
        return this.lastUpdatedUser;
    }
    
    public void setLastUpdatedUser(String lastUpdatedUser) {
        this.lastUpdatedUser = lastUpdatedUser;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbWbGameProfile")
    public Set<DlbWbGame> getDlbWbGames() {
        return this.dlbWbGames;
    }
    
    public void setDlbWbGames(Set<DlbWbGame> dlbWbGames) {
        this.dlbWbGames = dlbWbGames;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbWbGameProfile")
    public Set<DlbWbTicketFile> getDlbWbTicketFiles() {
        return this.dlbWbTicketFiles;
    }
    
    public void setDlbWbTicketFiles(Set<DlbWbTicketFile> dlbWbTicketFiles) {
        this.dlbWbTicketFiles = dlbWbTicketFiles;
    }




}


