package com.epic.dlb.model;
// Generated Jun 15, 2018 2:03:02 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DlbWbSystemPriviledgeId generated by hbm2java
 */
@Embeddable
public class DlbWbSystemPriviledgeId  implements java.io.Serializable {


     private String section;
     private String page;
     private String subsection;

    public DlbWbSystemPriviledgeId() {
    }

    public DlbWbSystemPriviledgeId(String section, String page, String subsection) {
       this.section = section;
       this.page = page;
       this.subsection = subsection;
    }
   


    @Column(name="SECTION", nullable=false, length=16)
    public String getSection() {
        return this.section;
    }
    
    public void setSection(String section) {
        this.section = section;
    }


    @Column(name="PAGE", nullable=false, length=16)
    public String getPage() {
        return this.page;
    }
    
    public void setPage(String page) {
        this.page = page;
    }


    @Column(name="SUBSECTION", nullable=false, length=16)
    public String getSubsection() {
        return this.subsection;
    }
    
    public void setSubsection(String subsection) {
        this.subsection = subsection;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DlbWbSystemPriviledgeId) ) return false;
		 DlbWbSystemPriviledgeId castOther = ( DlbWbSystemPriviledgeId ) other; 
         
		 return ( (this.getSection()==castOther.getSection()) || ( this.getSection()!=null && castOther.getSection()!=null && this.getSection().equals(castOther.getSection()) ) )
 && ( (this.getPage()==castOther.getPage()) || ( this.getPage()!=null && castOther.getPage()!=null && this.getPage().equals(castOther.getPage()) ) )
 && ( (this.getSubsection()==castOther.getSubsection()) || ( this.getSubsection()!=null && castOther.getSubsection()!=null && this.getSubsection().equals(castOther.getSubsection()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSection() == null ? 0 : this.getSection().hashCode() );
         result = 37 * result + ( getPage() == null ? 0 : this.getPage().hashCode() );
         result = 37 * result + ( getSubsection() == null ? 0 : this.getSubsection().hashCode() );
         return result;
   }   


}


