package com.epic.dlb.model;
// Generated Jun 15, 2018 2:03:02 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DlbWbMainDrawPrizeCodeId generated by hbm2java
 */
@Embeddable
public class DlbWbMainDrawPrizeCodeId implements java.io.Serializable {

    private String productCode;
    private String prizeCode;

    public DlbWbMainDrawPrizeCodeId() {
    }

    public DlbWbMainDrawPrizeCodeId(String productCode, String prizeCode) {
        this.productCode = productCode;
        this.prizeCode = prizeCode;
    }

    @Column(name = "PRODUCT_CODE", nullable = false, length = 16)
    public String getProductCode() {
        return this.productCode;
    }

    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    @Column(name = "PRIZE_CODE", nullable = false, length = 16)
    public String getPrizeCode() {
        return this.prizeCode;
    }

    public void setPrizeCode(String prizeCode) {
        this.prizeCode = prizeCode;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof DlbWbMainDrawPrizeCodeId)) {
            return false;
        }
        DlbWbMainDrawPrizeCodeId castOther = (DlbWbMainDrawPrizeCodeId) other;

        return ((this.getProductCode() == castOther.getProductCode()) || (this.getProductCode() != null && castOther.getProductCode() != null && this.getProductCode().equals(castOther.getProductCode())))
                && ((this.getPrizeCode() == castOther.getPrizeCode()) || (this.getPrizeCode() != null && castOther.getPrizeCode() != null && this.getPrizeCode().equals(castOther.getPrizeCode())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getProductCode() == null ? 0 : this.getProductCode().hashCode());
        result = 37 * result + (getPrizeCode() == null ? 0 : this.getPrizeCode().hashCode());
        return result;
    }

}
