package com.epic.dlb.model;
// Generated Jun 15, 2018 2:03:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DlbWbProductList generated by hbm2java
 */
@Entity
@Table(name="DLB_WB_PRODUCT_LIST"
    
)
public class DlbWbProductList  implements java.io.Serializable {


     private DlbWbProductListId id;
     private DlbStatus dlbStatus;
     private DlbWbProduct dlbWbProduct;
     private DlbWbWeekDay dlbWbWeekDay;
     private String lastUpdatedUser;
     private Date lastUpdatedTime;
     private Date createdTime;

    public DlbWbProductList() {
    }

	
    public DlbWbProductList(DlbWbProductListId id, DlbStatus dlbStatus, DlbWbProduct dlbWbProduct, DlbWbWeekDay dlbWbWeekDay) {
        this.id = id;
        this.dlbStatus = dlbStatus;
        this.dlbWbProduct = dlbWbProduct;
        this.dlbWbWeekDay = dlbWbWeekDay;
    }
    public DlbWbProductList(DlbWbProductListId id, DlbStatus dlbStatus, DlbWbProduct dlbWbProduct, DlbWbWeekDay dlbWbWeekDay, String lastUpdatedUser, Date lastUpdatedTime, Date createdTime) {
       this.id = id;
       this.dlbStatus = dlbStatus;
       this.dlbWbProduct = dlbWbProduct;
       this.dlbWbWeekDay = dlbWbWeekDay;
       this.lastUpdatedUser = lastUpdatedUser;
       this.lastUpdatedTime = lastUpdatedTime;
       this.createdTime = createdTime;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="productCode", column=@Column(name="PRODUCT_CODE", nullable=false, length=16) ), 
        @AttributeOverride(name="dayCode", column=@Column(name="DAY_CODE", nullable=false, length=16) ) } )
    public DlbWbProductListId getId() {
        return this.id;
    }
    
    public void setId(DlbWbProductListId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS", nullable=false)
    public DlbStatus getDlbStatus() {
        return this.dlbStatus;
    }
    
    public void setDlbStatus(DlbStatus dlbStatus) {
        this.dlbStatus = dlbStatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PRODUCT_CODE", nullable=false, insertable=false, updatable=false)
    public DlbWbProduct getDlbWbProduct() {
        return this.dlbWbProduct;
    }
    
    public void setDlbWbProduct(DlbWbProduct dlbWbProduct) {
        this.dlbWbProduct = dlbWbProduct;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DAY_CODE", nullable=false, insertable=false, updatable=false)
    public DlbWbWeekDay getDlbWbWeekDay() {
        return this.dlbWbWeekDay;
    }
    
    public void setDlbWbWeekDay(DlbWbWeekDay dlbWbWeekDay) {
        this.dlbWbWeekDay = dlbWbWeekDay;
    }

    
    @Column(name="LAST_UPDATED_USER", length=128)
    public String getLastUpdatedUser() {
        return this.lastUpdatedUser;
    }
    
    public void setLastUpdatedUser(String lastUpdatedUser) {
        this.lastUpdatedUser = lastUpdatedUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED_TIME", length=19)
    public Date getLastUpdatedTime() {
        return this.lastUpdatedTime;
    }
    
    public void setLastUpdatedTime(Date lastUpdatedTime) {
        this.lastUpdatedTime = lastUpdatedTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_TIME", length=19)
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }




}


