package com.epic.dlb.model;
// Generated Jun 15, 2018 2:03:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DlbWbUserRoleCategory generated by hbm2java
 */
@Entity
@Table(name="DLB_WB_USER_ROLE_CATEGORY"
    
)
public class DlbWbUserRoleCategory  implements java.io.Serializable {


     private String userrolecategorycode;
     private DlbStatus dlbStatus;
     private String description;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private Date createdtime;
     private Set<DlbWbUserRole> dlbWbUserRoles = new HashSet<DlbWbUserRole>(0);

    public DlbWbUserRoleCategory() {
    }

	
    public DlbWbUserRoleCategory(String userrolecategorycode) {
        this.userrolecategorycode = userrolecategorycode;
    }
    public DlbWbUserRoleCategory(String userrolecategorycode, DlbStatus dlbStatus, String description, String lastupdateduser, Date lastupdatedtime, Date createdtime, Set<DlbWbUserRole> dlbWbUserRoles) {
       this.userrolecategorycode = userrolecategorycode;
       this.dlbStatus = dlbStatus;
       this.description = description;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.createdtime = createdtime;
       this.dlbWbUserRoles = dlbWbUserRoles;
    }
   
     @Id 

    
    @Column(name="USERROLECATEGORYCODE", unique=true, nullable=false, length=16)
    public String getUserrolecategorycode() {
        return this.userrolecategorycode;
    }
    
    public void setUserrolecategorycode(String userrolecategorycode) {
        this.userrolecategorycode = userrolecategorycode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS")
    public DlbStatus getDlbStatus() {
        return this.dlbStatus;
    }
    
    public void setDlbStatus(DlbStatus dlbStatus) {
        this.dlbStatus = dlbStatus;
    }

    
    @Column(name="DESCRIPTION", length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="LASTUPDATEDUSER", length=128)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbWbUserRoleCategory")
    public Set<DlbWbUserRole> getDlbWbUserRoles() {
        return this.dlbWbUserRoles;
    }
    
    public void setDlbWbUserRoles(Set<DlbWbUserRole> dlbWbUserRoles) {
        this.dlbWbUserRoles = dlbWbUserRoles;
    }




}


