package com.epic.dlb.model;
// Generated Jun 15, 2018 2:03:02 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DlbWbSectionPriviledgeId generated by hbm2java
 */
@Embeddable
public class DlbWbSectionPriviledgeId  implements java.io.Serializable {


     private String userrole;
     private String section;

    public DlbWbSectionPriviledgeId() {
    }

    public DlbWbSectionPriviledgeId(String userrole, String section) {
       this.userrole = userrole;
       this.section = section;
    }
   


    @Column(name="USERROLE", nullable=false, length=16)
    public String getUserrole() {
        return this.userrole;
    }
    
    public void setUserrole(String userrole) {
        this.userrole = userrole;
    }


    @Column(name="SECTION", nullable=false, length=16)
    public String getSection() {
        return this.section;
    }
    
    public void setSection(String section) {
        this.section = section;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DlbWbSectionPriviledgeId) ) return false;
		 DlbWbSectionPriviledgeId castOther = ( DlbWbSectionPriviledgeId ) other; 
         
		 return ( (this.getUserrole()==castOther.getUserrole()) || ( this.getUserrole()!=null && castOther.getUserrole()!=null && this.getUserrole().equals(castOther.getUserrole()) ) )
 && ( (this.getSection()==castOther.getSection()) || ( this.getSection()!=null && castOther.getSection()!=null && this.getSection().equals(castOther.getSection()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserrole() == null ? 0 : this.getUserrole().hashCode() );
         result = 37 * result + ( getSection() == null ? 0 : this.getSection().hashCode() );
         return result;
   }   


}


