package com.epic.dlb.model;
// Generated Jun 15, 2018 2:03:02 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DlbWbEmployee generated by hbm2java
 */
@Entity
@Table(name = "DLB_WB_EMPLOYEE"
)
public class DlbWbEmployee implements java.io.Serializable {

    private String employeeid;
    private DlbStatus dlbStatus;
    private String name;
    private String nic;
    private String address;
    private String contactno;
    private String email;
    private String lastupdateduser;
    private Date lastupdatedtime;
    private Date createdtime;
    private String tokenPublicKey;
    private Set<DlbWbWiningFile> dlbWbWiningFilesForApprovedBy = new HashSet<DlbWbWiningFile>(0);
    private Set<DlbWbWiningFileHistory> dlbWbWiningFileHistoriesForUploadBy = new HashSet<DlbWbWiningFileHistory>(0);
    private Set<DlbWbTicketFile> dlbWbTicketFilesForUploadBy = new HashSet<DlbWbTicketFile>(0);
    private Set<DlbWbWiningFile> dlbWbWiningFilesForUploadBy = new HashSet<DlbWbWiningFile>(0);
    private Set<DlbWbWiningFileHistory> dlbWbWiningFileHistoriesForApprovedBy = new HashSet<DlbWbWiningFileHistory>(0);
    private Set<DlbWbWiningFileApprovalHistory> dlbWbWiningFileApprovalHistories = new HashSet<DlbWbWiningFileApprovalHistory>(0);
    private Set<DlbWbSystemUser> dlbWbSystemUsers = new HashSet<DlbWbSystemUser>(0);
    private Set<DlbWbTicketFile> dlbWbTicketFilesForApprovedBy = new HashSet<DlbWbTicketFile>(0);

    public DlbWbEmployee() {
    }

    public DlbWbEmployee(String employeeid) {
        this.employeeid = employeeid;
    }

    public DlbWbEmployee(String employeeid, DlbStatus dlbStatus, String name, String nic, String address, String contactno, String email, String lastupdateduser, Date lastupdatedtime, Date createdtime, String tokenPublicKey, Set<DlbWbWiningFile> dlbWbWiningFilesForApprovedBy, Set<DlbWbWiningFileHistory> dlbWbWiningFileHistoriesForUploadBy, Set<DlbWbTicketFile> dlbWbTicketFilesForUploadBy, Set<DlbWbWiningFile> dlbWbWiningFilesForUploadBy, Set<DlbWbWiningFileHistory> dlbWbWiningFileHistoriesForApprovedBy, Set<DlbWbWiningFileApprovalHistory> dlbWbWiningFileApprovalHistories, Set<DlbWbSystemUser> dlbWbSystemUsers, Set<DlbWbTicketFile> dlbWbTicketFilesForApprovedBy) {
        this.employeeid = employeeid;
        this.dlbStatus = dlbStatus;
        this.name = name;
        this.nic = nic;
        this.address = address;
        this.contactno = contactno;
        this.email = email;
        this.lastupdateduser = lastupdateduser;
        this.lastupdatedtime = lastupdatedtime;
        this.createdtime = createdtime;
        this.tokenPublicKey = tokenPublicKey;
        this.dlbWbWiningFilesForApprovedBy = dlbWbWiningFilesForApprovedBy;
        this.dlbWbWiningFileHistoriesForUploadBy = dlbWbWiningFileHistoriesForUploadBy;
        this.dlbWbTicketFilesForUploadBy = dlbWbTicketFilesForUploadBy;
        this.dlbWbWiningFilesForUploadBy = dlbWbWiningFilesForUploadBy;
        this.dlbWbWiningFileHistoriesForApprovedBy = dlbWbWiningFileHistoriesForApprovedBy;
        this.dlbWbWiningFileApprovalHistories = dlbWbWiningFileApprovalHistories;
        this.dlbWbSystemUsers = dlbWbSystemUsers;
        this.dlbWbTicketFilesForApprovedBy = dlbWbTicketFilesForApprovedBy;
    }

    @Id

    @Column(name = "EMPLOYEEID", unique = true, nullable = false, length = 16)
    public String getEmployeeid() {
        return this.employeeid;
    }

    public void setEmployeeid(String employeeid) {
        this.employeeid = employeeid;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "STATUS")
    public DlbStatus getDlbStatus() {
        return this.dlbStatus;
    }

    public void setDlbStatus(DlbStatus dlbStatus) {
        this.dlbStatus = dlbStatus;
    }

    @Column(name = "NAME", length = 128)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "NIC", length = 16)
    public String getNic() {
        return this.nic;
    }

    public void setNic(String nic) {
        this.nic = nic;
    }

    @Column(name = "ADDRESS", length = 256)
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Column(name = "CONTACTNO", length = 16)
    public String getContactno() {
        return this.contactno;
    }

    public void setContactno(String contactno) {
        this.contactno = contactno;
    }

    @Column(name = "EMAIL", length = 128)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "LASTUPDATEDUSER", length = 128)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }

    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LASTUPDATEDTIME", length = 19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }

    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATEDTIME", length = 19)
    public Date getCreatedtime() {
        return this.createdtime;
    }

    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    @Column(name = "TOKEN_PUBLIC_KEY", length = 65535)
    public String getTokenPublicKey() {
        return this.tokenPublicKey;
    }

    public void setTokenPublicKey(String tokenPublicKey) {
        this.tokenPublicKey = tokenPublicKey;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "dlbWbEmployeeByApprovedBy")
    public Set<DlbWbWiningFile> getDlbWbWiningFilesForApprovedBy() {
        return this.dlbWbWiningFilesForApprovedBy;
    }

    public void setDlbWbWiningFilesForApprovedBy(Set<DlbWbWiningFile> dlbWbWiningFilesForApprovedBy) {
        this.dlbWbWiningFilesForApprovedBy = dlbWbWiningFilesForApprovedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "dlbWbEmployeeByUploadBy")
    public Set<DlbWbWiningFileHistory> getDlbWbWiningFileHistoriesForUploadBy() {
        return this.dlbWbWiningFileHistoriesForUploadBy;
    }

    public void setDlbWbWiningFileHistoriesForUploadBy(Set<DlbWbWiningFileHistory> dlbWbWiningFileHistoriesForUploadBy) {
        this.dlbWbWiningFileHistoriesForUploadBy = dlbWbWiningFileHistoriesForUploadBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "dlbWbEmployeeByUploadBy")
    public Set<DlbWbTicketFile> getDlbWbTicketFilesForUploadBy() {
        return this.dlbWbTicketFilesForUploadBy;
    }

    public void setDlbWbTicketFilesForUploadBy(Set<DlbWbTicketFile> dlbWbTicketFilesForUploadBy) {
        this.dlbWbTicketFilesForUploadBy = dlbWbTicketFilesForUploadBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "dlbWbEmployeeByUploadBy")
    public Set<DlbWbWiningFile> getDlbWbWiningFilesForUploadBy() {
        return this.dlbWbWiningFilesForUploadBy;
    }

    public void setDlbWbWiningFilesForUploadBy(Set<DlbWbWiningFile> dlbWbWiningFilesForUploadBy) {
        this.dlbWbWiningFilesForUploadBy = dlbWbWiningFilesForUploadBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "dlbWbEmployeeByApprovedBy")
    public Set<DlbWbWiningFileHistory> getDlbWbWiningFileHistoriesForApprovedBy() {
        return this.dlbWbWiningFileHistoriesForApprovedBy;
    }

    public void setDlbWbWiningFileHistoriesForApprovedBy(Set<DlbWbWiningFileHistory> dlbWbWiningFileHistoriesForApprovedBy) {
        this.dlbWbWiningFileHistoriesForApprovedBy = dlbWbWiningFileHistoriesForApprovedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "dlbWbEmployee")
    public Set<DlbWbWiningFileApprovalHistory> getDlbWbWiningFileApprovalHistories() {
        return this.dlbWbWiningFileApprovalHistories;
    }

    public void setDlbWbWiningFileApprovalHistories(Set<DlbWbWiningFileApprovalHistory> dlbWbWiningFileApprovalHistories) {
        this.dlbWbWiningFileApprovalHistories = dlbWbWiningFileApprovalHistories;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "dlbWbEmployee")
    public Set<DlbWbSystemUser> getDlbWbSystemUsers() {
        return this.dlbWbSystemUsers;
    }

    public void setDlbWbSystemUsers(Set<DlbWbSystemUser> dlbWbSystemUsers) {
        this.dlbWbSystemUsers = dlbWbSystemUsers;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "dlbWbEmployeeByApprovedBy")
    public Set<DlbWbTicketFile> getDlbWbTicketFilesForApprovedBy() {
        return this.dlbWbTicketFilesForApprovedBy;
    }

    public void setDlbWbTicketFilesForApprovedBy(Set<DlbWbTicketFile> dlbWbTicketFilesForApprovedBy) {
        this.dlbWbTicketFilesForApprovedBy = dlbWbTicketFilesForApprovedBy;
    }

}
