package com.epic.dlb.model;
// Generated Jun 15, 2018 2:03:02 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DlbWbProductListId generated by hbm2java
 */
@Embeddable
public class DlbWbProductListId  implements java.io.Serializable {


     private String productCode;
     private String dayCode;

    public DlbWbProductListId() {
    }

    public DlbWbProductListId(String productCode, String dayCode) {
       this.productCode = productCode;
       this.dayCode = dayCode;
    }
   


    @Column(name="PRODUCT_CODE", nullable=false, length=16)
    public String getProductCode() {
        return this.productCode;
    }
    
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }


    @Column(name="DAY_CODE", nullable=false, length=16)
    public String getDayCode() {
        return this.dayCode;
    }
    
    public void setDayCode(String dayCode) {
        this.dayCode = dayCode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DlbWbProductListId) ) return false;
		 DlbWbProductListId castOther = ( DlbWbProductListId ) other; 
         
		 return ( (this.getProductCode()==castOther.getProductCode()) || ( this.getProductCode()!=null && castOther.getProductCode()!=null && this.getProductCode().equals(castOther.getProductCode()) ) )
 && ( (this.getDayCode()==castOther.getDayCode()) || ( this.getDayCode()!=null && castOther.getDayCode()!=null && this.getDayCode().equals(castOther.getDayCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getProductCode() == null ? 0 : this.getProductCode().hashCode() );
         result = 37 * result + ( getDayCode() == null ? 0 : this.getDayCode().hashCode() );
         return result;
   }   


}


