package com.epic.dlb.model;
// Generated Mar 27, 2020 3:49:15 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * DlbWbGamePrize generated by hbm2java
 */
@Entity
@Table(name="DLB_WB_GAME_PRIZE"
   
)
public class DlbWbGamePrize  implements java.io.Serializable {


     private Integer id;
     private Date timestamp;
     private DlbStatus dlbStatus;
     private DlbWbGame dlbWbGame;
     private DlbWbGamePrizeType dlbWbGamePrizeType;
     private Double amount;

    public DlbWbGamePrize() {
    }

	
    public DlbWbGamePrize(DlbWbGame dlbWbGame) {
        this.dlbWbGame = dlbWbGame;
    }
    public DlbWbGamePrize(DlbStatus dlbStatus, DlbWbGame dlbWbGame, DlbWbGamePrizeType dlbWbGamePrizeType, Double amount) {
       this.dlbStatus = dlbStatus;
       this.dlbWbGame = dlbWbGame;
       this.dlbWbGamePrizeType = dlbWbGamePrizeType;
       this.amount = amount;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Version@Temporal(TemporalType.TIMESTAMP)
    @Column(name="TIMESTAMP", length=19)
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS")
    public DlbStatus getDlbStatus() {
        return this.dlbStatus;
    }
    
    public void setDlbStatus(DlbStatus dlbStatus) {
        this.dlbStatus = dlbStatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GAME_ID", nullable=false)
    public DlbWbGame getDlbWbGame() {
        return this.dlbWbGame;
    }
    
    public void setDlbWbGame(DlbWbGame dlbWbGame) {
        this.dlbWbGame = dlbWbGame;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PRIZE_TYPE")
    public DlbWbGamePrizeType getDlbWbGamePrizeType() {
        return this.dlbWbGamePrizeType;
    }
    
    public void setDlbWbGamePrizeType(DlbWbGamePrizeType dlbWbGamePrizeType) {
        this.dlbWbGamePrizeType = dlbWbGamePrizeType;
    }

    
    @Column(name="AMOUNT", precision=10)
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }




}


