package com.epic.dlb.model;
// Generated Jun 15, 2018 2:03:02 PM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DlbWbResult generated by hbm2java
 */
@Entity
@Table(name="DLB_WB_RESULT"
    
)
public class DlbWbResult  implements java.io.Serializable {


     private Integer id;
     private DlbStatus dlbStatus;
     private DlbWbProduct dlbWbProduct;
     private DlbWbProductProfile dlbWbProductProfile;
     private DlbWbWeekDay dlbWbWeekDay;
     private DlbSwtStWinningLogic dlbSwtStWinningLogic;
     private int drawNo;
     private Date date;
     private String lastUpdatedUser;
     private Date lastUpdatedTime;
     private Date createdTime;
     private String nextJackpot;
     private String nextDate;
     private List<DlbWbResultDetails> dlbWbResultDetailses = new ArrayList<DlbWbResultDetails>();

    public DlbWbResult() {
    }

	
    public DlbWbResult(DlbStatus dlbStatus, DlbWbProduct dlbWbProduct, DlbWbProductProfile dlbWbProductProfile, DlbWbWeekDay dlbWbWeekDay, int drawNo) {
        this.dlbStatus = dlbStatus;
        this.dlbWbProduct = dlbWbProduct;
        this.dlbWbProductProfile = dlbWbProductProfile;
        this.dlbWbWeekDay = dlbWbWeekDay;
        this.drawNo = drawNo;
    }
   
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS", nullable=false)
    public DlbStatus getDlbStatus() {
        return this.dlbStatus;
    }
    
    public void setDlbStatus(DlbStatus dlbStatus) {
        this.dlbStatus = dlbStatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PRODUCT", nullable=false)
    public DlbWbProduct getDlbWbProduct() {
        return this.dlbWbProduct;
    }
    
    public void setDlbWbProduct(DlbWbProduct dlbWbProduct) {
        this.dlbWbProduct = dlbWbProduct;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PROFILE_ID", nullable=false)
    public DlbWbProductProfile getDlbWbProductProfile() {
        return this.dlbWbProductProfile;
    }
    
    public void setDlbWbProductProfile(DlbWbProductProfile dlbWbProductProfile) {
        this.dlbWbProductProfile = dlbWbProductProfile;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DAY", nullable=false)
    public DlbWbWeekDay getDlbWbWeekDay() {
        return this.dlbWbWeekDay;
    }
    
    public void setDlbWbWeekDay(DlbWbWeekDay dlbWbWeekDay) {
        this.dlbWbWeekDay = dlbWbWeekDay;
    }

    
    @Column(name="DRAW_NO", nullable=false)
    public int getDrawNo() {
        return this.drawNo;
    }
    
    public void setDrawNo(int drawNo) {
        this.drawNo = drawNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE", length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="LAST_UPDATED_USER", length=128)
    public String getLastUpdatedUser() {
        return this.lastUpdatedUser;
    }
    
    public void setLastUpdatedUser(String lastUpdatedUser) {
        this.lastUpdatedUser = lastUpdatedUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED_TIME", length=19)
    public Date getLastUpdatedTime() {
        return this.lastUpdatedTime;
    }
    
    public void setLastUpdatedTime(Date lastUpdatedTime) {
        this.lastUpdatedTime = lastUpdatedTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_TIME", length=19)
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    
    @Column(name="NEXT_JACKPOT", length=45)
    public String getNextJackpot() {
        return this.nextJackpot;
    }
    
    public void setNextJackpot(String nextJackpot) {
        this.nextJackpot = nextJackpot;
    }

    
    @Column(name="NEXT_DATE", length=45)
    public String getNextDate() {
        return this.nextDate;
    }
    
    public void setNextDate(String nextDate) {
        this.nextDate = nextDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dlbWbResult")
    public List<DlbWbResultDetails> getDlbWbResultDetailses() {
        return this.dlbWbResultDetailses;
    }
    
    public void setDlbWbResultDetailses(List<DlbWbResultDetails> dlbWbResultDetailses) {
        this.dlbWbResultDetailses = dlbWbResultDetailses;
    }
//
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="WINNING_LOGIC_ID", nullable=false)
    public DlbSwtStWinningLogic getDlbSwtStWinningLogic() {
        return dlbSwtStWinningLogic;
    }

    public void setDlbSwtStWinningLogic(DlbSwtStWinningLogic dlbSwtStWinningLogic) {
        this.dlbSwtStWinningLogic = dlbSwtStWinningLogic;
    }

    



}


