package com.epic.dlb.model;
// Generated Jun 15, 2018 2:03:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DlbWbWiningFileApprovalHistory generated by hbm2java
 */
@Entity
@Table(name="DLB_WB_WINING_FILE_APPROVAL_HISTORY"
    
)
public class DlbWbWiningFileApprovalHistory  implements java.io.Serializable {


     private Integer id;
     private DlbStatus dlbStatus;
     private DlbWbEmployee dlbWbEmployee;
     private DlbWbWiningFile dlbWbWiningFile;
     private DlbWbWorkflow dlbWbWorkflowByDestinationStage;
     private DlbWbWorkflow dlbWbWorkflowByInitialStage;
     private String lastUpdatedUser;
     private Date lastUpdatedTime;
     private Date createdTime;

    public DlbWbWiningFileApprovalHistory() {
    }

	
    public DlbWbWiningFileApprovalHistory(DlbWbEmployee dlbWbEmployee, DlbWbWiningFile dlbWbWiningFile, DlbWbWorkflow dlbWbWorkflowByDestinationStage, DlbWbWorkflow dlbWbWorkflowByInitialStage) {
        this.dlbWbEmployee = dlbWbEmployee;
        this.dlbWbWiningFile = dlbWbWiningFile;
        this.dlbWbWorkflowByDestinationStage = dlbWbWorkflowByDestinationStage;
        this.dlbWbWorkflowByInitialStage = dlbWbWorkflowByInitialStage;
    }
    public DlbWbWiningFileApprovalHistory(DlbStatus dlbStatus, DlbWbEmployee dlbWbEmployee, DlbWbWiningFile dlbWbWiningFile, DlbWbWorkflow dlbWbWorkflowByDestinationStage, DlbWbWorkflow dlbWbWorkflowByInitialStage, String lastUpdatedUser, Date lastUpdatedTime, Date createdTime) {
       this.dlbStatus = dlbStatus;
       this.dlbWbEmployee = dlbWbEmployee;
       this.dlbWbWiningFile = dlbWbWiningFile;
       this.dlbWbWorkflowByDestinationStage = dlbWbWorkflowByDestinationStage;
       this.dlbWbWorkflowByInitialStage = dlbWbWorkflowByInitialStage;
       this.lastUpdatedUser = lastUpdatedUser;
       this.lastUpdatedTime = lastUpdatedTime;
       this.createdTime = createdTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ACTION")
    public DlbStatus getDlbStatus() {
        return this.dlbStatus;
    }
    
    public void setDlbStatus(DlbStatus dlbStatus) {
        this.dlbStatus = dlbStatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMPLOYEEID", nullable=false)
    public DlbWbEmployee getDlbWbEmployee() {
        return this.dlbWbEmployee;
    }
    
    public void setDlbWbEmployee(DlbWbEmployee dlbWbEmployee) {
        this.dlbWbEmployee = dlbWbEmployee;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="WINING_FILE_ID", nullable=false)
    public DlbWbWiningFile getDlbWbWiningFile() {
        return this.dlbWbWiningFile;
    }
    
    public void setDlbWbWiningFile(DlbWbWiningFile dlbWbWiningFile) {
        this.dlbWbWiningFile = dlbWbWiningFile;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DESTINATION_STAGE", nullable=false)
    public DlbWbWorkflow getDlbWbWorkflowByDestinationStage() {
        return this.dlbWbWorkflowByDestinationStage;
    }
    
    public void setDlbWbWorkflowByDestinationStage(DlbWbWorkflow dlbWbWorkflowByDestinationStage) {
        this.dlbWbWorkflowByDestinationStage = dlbWbWorkflowByDestinationStage;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="INITIAL_STAGE", nullable=false)
    public DlbWbWorkflow getDlbWbWorkflowByInitialStage() {
        return this.dlbWbWorkflowByInitialStage;
    }
    
    public void setDlbWbWorkflowByInitialStage(DlbWbWorkflow dlbWbWorkflowByInitialStage) {
        this.dlbWbWorkflowByInitialStage = dlbWbWorkflowByInitialStage;
    }

    
    @Column(name="LAST_UPDATED_USER", length=128)
    public String getLastUpdatedUser() {
        return this.lastUpdatedUser;
    }
    
    public void setLastUpdatedUser(String lastUpdatedUser) {
        this.lastUpdatedUser = lastUpdatedUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED_TIME", length=19)
    public Date getLastUpdatedTime() {
        return this.lastUpdatedTime;
    }
    
    public void setLastUpdatedTime(Date lastUpdatedTime) {
        this.lastUpdatedTime = lastUpdatedTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_TIME", length=19)
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }




}


